### ISSUE TITLE
per test sharding?

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#1]
> Instead of creating one shard per test case Flank can create shards that contain tests that add up to a given duration

Is it not possible to have one shard per test case? In terms of fault isolation/video/logs, there are some use cases where this is desirable.

**Comment by renas** [comment]
It is possible through a properties file. To enable one test per shard set shard-duration to -1. Please see the Readme for more information.

**Comment by bootstraponline** [comment]
Ok, thanks!
