### ISSUE TITLE
Aggregated report throws a runtime error

### ISSUE THREAD

**Issue by ryanzor** [TestArmada/flank#100]
> Can't process test artifacts for: testSurfaceLogging
> Can't process test artifacts for: testAppQuitViaActivityFinish
> Can't process test artifacts for: testSaveObstruction
> Can't process test artifacts for: testOverflowObstruction
> Can't process test artifacts for: testTriedItEndsImpressions
> Can't process test artifacts for: testSaveObstruction
> Can't process test artifacts for: testSaveObstruction
> java.lang.RuntimeException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /project/bucket/2018-01-24_18:01:44.378000_Mlhf/41/NexusLowRes-25-en-portrait/logcat

The xml aggregated and uploaded fine.  I, unfortunately, don't know if the not found file was ever created.  I believe that the can't process test artifacts were all shards that partially failed.

**Comment by renas** [comment]
@rciovati can you please have a look at this?

**Comment by rciovati** [comment]
Hey @ryanzor, thanks for using the test aggregation feature and reporting issues :) 

Could you please provide the full tracktrace? We have a theory around why this is happening but we'd like to make sure there is not something else going on.

**Comment by ryanzor** [comment]
Thanks for building the test aggregation feature!

Full trace from the most recent case:

```

java.lang.RuntimeException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /project/bucket/2018-01-25_17:28:48.977000_dtGC/45/NexusLowRes-25-en-portrait/logcat
--
  | at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  | at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  | at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  | at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  | at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
  | at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
  | at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
  | at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
  | at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
  | at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
  | at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
  | at com.walmart.otto.aggregator.ReportsAggregator.aggregate(ReportsAggregator.java:66)
  | at com.walmart.otto.Flank.aggregateTestReports(Flank.java:90)
  | at java.util.Optional.ifPresent(Optional.java:159)
  | at com.walmart.otto.Flank.start(Flank.java:79)
  | at com.walmart.otto.Flank.main(Flank.java:107)
  | Caused by: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /project/bucket/2018-01-25_17:28:48.977000_dtGC/45/NexusLowRes-25-en-portrait/logcat
  | at com.walmart.otto.aggregator.ReportsAggregator.processArtifacts(ReportsAggregator.java:95)
  | at com.walmart.otto.aggregator.ReportsAggregator.lambda$aggregate$4(ReportsAggregator.java:66)
  | at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
  | at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
  | at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
  | at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
  | at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
  | at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
  | at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
  | at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
  | at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
  | at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
  | at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
  | at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
  | at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
  | Caused by: java.nio.file.NoSuchFileException: /project/bucket/2018-01-25_17:28:48.977000_dtGC/45/NexusLowRes-25-en-portrait/logcat
  | at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
  | at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
  | at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
  | at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:526)
  | at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
  | at java.nio.file.Files.copy(Files.java:1274)
  | at com.walmart.otto.aggregator.ArtifactsProcessor.generateArtifactsForTestCase(ArtifactsProcessor.java:60)
  | at com.walmart.otto.aggregator.ReportsAggregator.processArtifacts(ReportsAggregator.java:92)
  | ... 14 more

```

I did the google cloud bucket for `/project/bucket/2018-01-25_17:28:48.977000_dtGC/45/NexusLowRes-25-en-portrait/logcat` in the above error and logcat is there.  Checking the local version in the bucket folder, I have a file `logcat_.gstmp` that is zero bytes.

**Comment by bootstraponline** [comment]
should be fixed by https://github.com/TestArmada/flank/pull/103

**Comment by rciovati** [comment]
Thanks for the stacktrace!
The problem you hit is exactly the one fixed by #103. 

I am still not sure why gsutil doesn't properly pull the logcat. Does the file exist in the bucket?

**Comment by ryanzor** [comment]
I tried the newest apk and got a brand new problem

```
java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:97)
	at com.walmart.otto.aggregator.HtmlReport.generate(HtmlReport.java:75)
	at com.walmart.otto.aggregator.ReportsAggregator.aggregate(ReportsAggregator.java:68)
	at com.walmart.otto.Flank.aggregateTestReports(Flank.java:98)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.walmart.otto.Flank.start(Flank.java:87)
	at com.walmart.otto.Flank.main(Flank.java:118)
```

After playing around with it for a bit I think we were misdiagnosing the problem.  I was getting the issue consistently after a regression showed up, the regression caused some of my tests to timeout.  After adjusting my sharding strategy to avoid the timeout the html report seems to generate fine.

So I'm thinking the issue is that the html report generate doesn't handle timeouts.

**Comment by rciovati** [comment]
The exception you got now is quite weird because looks like it fails reading the html template that is bundled as a resource in the Flank jar. How did you build Flank?

> After playing around with it for a bit I think we were misdiagnosing the problem. I was getting the issue consistently after a regression showed up, the regression caused some of my tests to timeout. After adjusting my sharding strategy to avoid the timeout the html report seems to generate fine.

We should probably better support this use case because when your shard fails for a timeout TFL doesn't generate the artifacts (Junit reports, logcat, etc) for the execution. On our side, we decided not to use the TFL timeout but the `@Timeout` Junit rule to prevent this situation.

I'll try to work on some improvements a look once I'm back from vacation.

**Comment by ryanzor** [comment]
I built with

`./gradlew -p Flank clean build`

Adding our own timeout seems like an easy step to do regardless.

**Comment by runningcode** [comment]
I just tried the 2.0.0 build and got a similar error
```
Generating combined reports starting from: /home/travis/build/zenjob/zenjob-android/app/build/flank/bucket/2018-01-31_10:48:16.680000_zUSA
[Fatal Error] test_result_0.xml_.gstmp:1:1: Premature end of file.
java.lang.NullPointerException
	at com.walmart.otto.aggregator.JunitReport.readTestCases(JunitReport.java:153)
	at com.walmart.otto.aggregator.JunitReport.readTestSuite(JunitReport.java:131)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.walmart.otto.aggregator.ReportsAggregator.readTestSuites(ReportsAggregator.java:100)
	at com.walmart.otto.aggregator.ReportsAggregator.aggregate(ReportsAggregator.java:39)
	at com.walmart.otto.Flank.aggregateTestReports(Flank.java:98)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.walmart.otto.Flank.start(Flank.java:87)
	at com.walmart.otto.Flank.main(Flank.java:118)
```

**Comment by bootstraponline** [comment]
> All downloads are now written to a temporary file with a "_.gstmp" suffix while the download is still in progress. 
>
> https://github.com/GoogleCloudPlatform/gsutil/blob/master/CHANGES.md

I think JunitReport is somehow parsing temp files instead of waiting for the xml to finish downloading.

**Comment by rciovati** [comment]
> I think JunitReport is somehow parsing temp files instead of waiting for the xml to finish downloading.

We assume that once the gsutil command completes the download is finished but apparently is not always the case. I'll try to figure out whats going on there.

**Comment by bootstraponline** [comment]
Hi, thanks for opening an issue on the Flank repo. The Kotlin rewrite is now available for testing and feedback. This replaces the Java version of Flank.

- https://github.com/TestArmada/flank/releases/tag/flank_snapshot

Join us in the`#flank` channel on the Firebase slack to chat. If this is still an issue in the new release, comment and let me know.

-  https://firebase.community/
