### ISSUE TITLE
[Feature] Cost estimate

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#11]
> Combined test execution time: 26 seconds
>
> seconds are round up to minutes by Firebase test lab

thoughts on having flank output estimated cost for the test run? The combined test execution time isn't sufficient to figure out the expense. The output would look something like this:

> Estimated cost: $0.033 (virtual), $0.166 (physical)

2 tests at <1 min each
-  `1/60.0 * 2 = $0.033`  virtual device
- `5/60.0 * 2 = $0.166` physical device

**Comment by renas** [comment]
I like this idea. Let's see what we can do.

**Comment by bootstraponline** [comment]
> Combined test execution time: 2551 seconds

maybe output the billing time to the console? I just incurred a charge of 112 minutes but it's difficult to tell that from the existing flank output. The execution time is only ~42.5m but then there's that rounding rule.

it'd also be nice to format these seconds into minutes.

**Comment by renas** [comment]
We'll format the seconds to minutes. I like the idea. It would be beneficial to know how much a test run costs. We'll look into it next week.

**Comment by bootstraponline** [comment]
fixed by https://github.com/TestArmada/flank/issues/20
