### ISSUE TITLE
FTL | JUnit test time is always zero

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#12]
The timing info in the results.xml files is wrong. Firebase is aware of the issue but they probably won't fix it anytime soon. I think overriding the xml files with the actual time as recorded by flank might be helpful. This would allow, among other things, accurate cost estimation.

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<testsuite errors="0" failures="0" hostname="localhost" name="" skipped="0" tests="2" time="1.823" timestamp="2017-05-26T15:40:36">
  <properties/>
  <testcase classname="com.instructure.teacher.ui.DeviceTest" name="checkAnimationsOff [NexusLowRes-25-en-portrait]" time="0.0"/>
  <testcase classname="com.instructure.teacher.ui.DeviceTest" name="displaysPageObjects [NexusLowRes-25-en-portrait]" time="0.0"/>
</testsuite>
```

The issue is `time="0.0"` which isn't true.

**Comment by renas** [comment]
Thanks, we'll have a look at this.

**Comment by bootstraponline** [comment]
FTL will fix this early Q3 2018.

**Comment by bootstraponline** [comment]
Update: FTL is still working on this.

**Comment by bootstraponline** [comment]
Fixed
