### ISSUE TITLE
Test with annotations doesn't work.

### ISSUE THREAD

**Issue by niranjani23** [TestArmada/flank#120]
I tried to filter my tests with annotation: 
`java -jar other/Flank-2.0.0.jar -a ${APK_FILE} -t ${TEST_APK_FILE} -f "package com.release.tests; annotation Staging" -c config.properties`
And the above command returns: 

> java.lang.IllegalStateException: No tests to run!
>   | at com.walmart.otto.Flank.getTestCaseNames(Flank.java:282)
>   | at com.walmart.otto.Flank.start(Flank.java:71)
>   | at com.walmart.otto.Flank.main(Flank.java:118)

This is my Staging.java: 
`@RunWith(Categories.class)
@Categories.IncludeCategory(Staging.class)
@Suite.SuiteClasses({
        com.release.tests.ReleaseTests.class
})

public class Staging {
}
`
My test class has the @Staging annotation added as well. 
What am I missing? How to call tests using annotations?

**Comment by renas** [comment]
Thanks for reporting this. What happens if you do like this: 

java -jar other/Flank-2.0.0.jar -a ${APK_FILE} -t ${TEST_APK_FILE} -f "annotation Staging" -c config.properties

**Comment by rciovati** [comment]
Also, make sure you are using the fully qualified name: `com.yourpackage.Staging`.

**Comment by niranjani23** [comment]
Thanks for your quick response! 
I still see the same error. Any other thoughts?

> 

+ java -jar other/Flank-2.0.0.jar -a /apk/debug.apk -t build/artifacts/apk/debug-androidTest.apk -f 'annotation com.release.Staging' -c config.properties
--
  | java.lang.IllegalStateException: No tests to run!
  | at com.walmart.otto.Flank.getTestCaseNames(Flank.java:282)
  | at com.walmart.otto.Flank.start(Flank.java:71)
  | at com.walmart.otto.Flank.main(Flank.java:118)

**Comment by bootstraponline** [comment]
Hi, thanks for opening an issue on the Flank repo. The Kotlin rewrite is now available for testing and feedback. This replaces the Java version of Flank.

- https://github.com/TestArmada/flank/releases/tag/flank_snapshot

Join us in the`#flank` channel on the Firebase slack to chat. If this is still an issue in the new release, comment and let me know.

-  https://firebase.community/
