### ISSUE TITLE
[Feature] Run all tests

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#13]
> java -jar flank.jar app.apk test.apk
> Usage: Flank <app-apk> <test-apk> <package-name>

I'd expect ^ to run all tests. Instead I have to specify a package. Thoughts on allowing all tests to run when the package is omitted? This is more in line with the gcloud CLI. Package is optional and default is to run everything.

**Comment by renas** [comment]
I like the idea. Lets see what we can do.
