### ISSUE TITLE
[Feature] Retry failed tests automatically

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#15]
It looks like there's no option to retry failed tests? That'd be helpful when 1 test runs in each VM (`shard-duration: -1`).

**Comment by renas** [comment]
Thanks for reporting this. This is in our backlog. We will add support for retries for all use cases.

**Comment by bootstraponline** [comment]
Test retry via a JUnit Rule seems to be the best approach. VM level retry is too slow due to the overhead of creating a VM.

**Comment by rciovati** [comment]
>Test retry via a JUnit Rule seems to be the best approach. VM level retry is too slow due to the overhead of creating a VM.

I agree that retrying failed tests using a JUnit Rule is probably the _easiest_ solution, I would not exclude implementing a mechanism that retries failed tests in a single VM. Using just a Rule is not possible to reach a truly clear state and in some use-cases it's desirable to have so. Now, I'm not saying that everybody should use this feature, but still, in my opinion, it's a nice-to-have.

**Comment by bootstraponline** [comment]
> Using just a Rule is not possible to reach a truly clear state 

With app reset & orchestrator a clear state is possible.

The issue with VM retry is it's slow and flaky. The chance for infrastructure failures increases.
