### ISSUE TITLE
Seperate the Kotlin project entirely from the Java project

### ISSUE THREAD

**Issue by sridoodla** [TestArmada/flank#151]
As they are essentially very different implementations, they should be as separated as possible. The options are -

#### Pros
- Distinct issues/pull requests and it is immediately clear what you are contributing to.
- Better project structure. No need for symlinking `gradlew`.
- Distinct CI for each project
- Very easy to switch/mark Java deprecated once Kotlin is prod ready.

#### Cons
- Can't think of any, atm.

#### Pros
- Better project structure. No need for symlinking `gradlew`.
- Distinct CI for each branch.
- Better pull requests. Easily clear where it is going.

#### Cons
- Not as easy to mark the old Java code deprecated. It will have to be removed and we lose code visibility to be limited to an old commit.
- Issues/Pull requests not as distinct as having a separate repository.

**Comment by bootstraponline** [comment]
I like the repo idea vs a long lived branch. I think we should probably chat with the TestArmada folks to see if they have a preference.

**Comment by bootstraponline** [comment]
After chatting with the team, there's a preference to have visibility on all Flank related work in one repository. One stop shop for all the Flank activities.

If you have ideas for improving things in the mono repository, I'd be open to them. Thanks for all your work on Flank.

More info on mono repos:
- https://eng.uber.com/ios-monorepo/

**Comment by sridoodla** [comment]
The thing with mono repos is that they are necessary when _some_ code is shared. In this case, no code is shared between the Kotlin and Java projects. They even have separate CI.

**Comment by bootstraponline** [comment]
I think there are efficiency gains to mono repos even without code sharing. The bigger companies like Google throw everything into one giant repo.

I've used both approaches in the past, there are pros/cons to each. I think it'd be less productive to have to check two locations for pull requests / issues. Most FTL bugs are going to apply to Kotlin & Java. 

We'd want all the Flank Java features in Kotlin someday. If someone has a feature idea for Java, then I'd want to know about it for Kotlin. Hopefully that makes sense in terms of the benefits. The downside is there's a bit more activity in the repo.
