### ISSUE TITLE
Running in different locales is painful

### ISSUE THREAD

**Issue by Macarse** [TestArmada/flank#153]
After getting translations back we run all the tests in different locales.
The properties file's device section looks like this:

```
devices=model:Nexus6P;version:23;orientation:portrait;locale:en_GB,\
model:Nexus6P;version:23;orientation:portrait;locale:cs_CZ,\
model:Nexus6P;version:23;orientation:portrait;locale:da_DK,\
model:Nexus6P;version:23;orientation:portrait;locale:de_DE,\
model:Nexus6P;version:23;orientation:portrait;locale:es_ES,\
model:Nexus6P;version:23;orientation:portrait;locale:fi_FI,\
model:Nexus6P;version:23;orientation:portrait;locale:fr_FR,\
model:Nexus6P;version:23;orientation:portrait;locale:fr_CA,\
model:Nexus6P;version:23;orientation:portrait;locale:it_IT,\
model:Nexus6P;version:23;orientation:portrait;locale:nl_NL,\
model:Nexus6P;version:23;orientation:portrait;locale:tr_TR,\
model:Nexus6P;version:23;orientation:portrait;locale:nb_NO,\
model:Nexus6P;version:23;orientation:portrait;locale:pl_PL,\
model:Nexus6P;version:23;orientation:portrait;locale:pt_PT,\
model:Nexus6P;version:23;orientation:portrait;locale:zh_CN,\
```

Can you think of a way to improve this?

**Comment by bootstraponline** [comment]
What does that look like when you use gcloud directly?

**Comment by Macarse** [comment]
You are asking what flank outputs as gcloud command?

**Comment by bootstraponline** [comment]
I'm saying if you were to run the same command using gcloud directly, what would that look like?

- https://cloud.google.com/sdk/gcloud/reference/firebase/test/android/run

**Comment by Macarse** [comment]
I haven't tried but I guess it would look the same. `--locales` was deprecated :(

Question: flank tries to make properties as similar as gcloud params or there is space for flexibility?

**Comment by bootstraponline** [comment]
Flank Java is a wrapper for gcloud. Any deviation comes at the expense of high maintenance costs for the team. I don't think it'd be in the best long term interests of the project to create a new way of specifying devices that's unique to flank.

If you have that discussion with the gcloud team then of course we'd be happy to adapt and follow the upstream decision.

**Comment by Macarse** [comment]
@bootstraponline makes sense. Thanks for your time.
