### ISSUE TITLE
The flank.tests file is generated incorrectly

### ISSUE THREAD

**Issue by tasmonzo** [TestArmada/flank#162]
We have a relatively large amount of tests (144). We've been using the automatic configuration of shards up to now, specifically:
```
shard-timeout=5
shard-duration=120
```
This would generate about 24 shards to run our tests into, and it had been working fine for some time. Recently though, our tests started failing. It looked like flank would try to generate 89 shards, and run 88 tests in individual shards, while the rest would all run in one shard. When I had a look at the `flank.tests` file, it looked like it was missing quite a few tests and the time for all of the ones that were there was set to 0!

Setting the number of shards manually seems to fix the issue:
```
numShards=25
```
But it would still be preferable to have this configured automatically...

To make things clear, we have not made dramatic changes to our test suite lately. The only recent change I found, was removing 4 tests.

**Comment by bootstraponline** [comment]
Hi, thanks for opening an issue on the Flank repo. The Kotlin rewrite is now available for testing and feedback. This replaces the Java version of Flank.

- https://github.com/TestArmada/flank/releases/tag/flank_snapshot

Join us in the`#flank` channel on the Firebase slack to chat. If this is still an issue in the new release, comment and let me know.

-  https://firebase.community/
