### ISSUE TITLE
Kotlin | Make GOOGLE_CLOUD_PROJECT optional

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#166]
GOOGLE_CLOUD_PROJECT is required to be defined (or for the gcloud sdk to be installed), even if project id is already set in the yaml config.

**Comment by bootstraponline** [comment]
> IIUC this is optional and Flank should be able to pull project ID from service account credentials

it should be pulling from the service account credentials, try on the Flank snapshot release and let me know. If it's not auto detected then that's a bug.

**Comment by tir38** [comment]
Actually I think it's Fladle not working: https://github.com/runningcode/fladle/issues/16
