### ISSUE TITLE
Support running by package & class

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#175]
com.example.MyClass should be a valid test target. Currently the test method detection will flag it as a method and prevent execution.

https://cloud.google.com/sdk/gcloud/reference/firebase/test/android/run

![image](https://user-images.githubusercontent.com/1173057/41739015-c94daa50-7561-11e8-857c-635026862260.png)

I think something like this YAML may allow us to exactly match the gcloud CLI. Note that the validation logic on Android will need to be reworked to take into account `package/class/test` method. iOS validation is only able to support `method_name` right now

```
testTargets:
 - package package_name
 - class package_name.class_name
 - class package_name.class_name#method_name
```

**Comment by winterDroid** [comment]
What about `annotation` and the `notXXX` cases?

**Comment by bootstraponline** [comment]
> What about annotation and the notXXX cases?

That sounds like a new feature request.
