### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by Macarse** [TestArmada/flank#178]
In google io 2018, firebase test lab for iOS was announced.
More info at: https://firebase.google.com/docs/test-lab/ios/firebase-console

I am more than happy to help with the implementation.
For maintainers: Do you think the iOS support can live inside this project?

**Comment by bootstraponline** [comment]
Absolutely, I'm waiting on firebase test lab to white list my account.

**Comment by Macarse** [comment]
@bootstraponline perfect! Same thing here. 
Have you though on what to use to replace `dex-test-parser`?

I am not 100% we can parse all tests from `.xctest` package

**Comment by bootstraponline** [comment]
I think we can parse them all: https://github.com/linkedin/bluepill/issues/258

Otherwise we could fall back to AST parsing.

**Comment by bootstraponline** [comment]
I've been added to the beta. :) I'll check this out next week.

**Comment by Macarse** [comment]
@bootstraponline I just recreated the client and there is no reference to "ios". Shouldn't we wait for May 16th for this?

**Comment by bootstraponline** [comment]
It looks like https://www.googleapis.com/discovery/v1/apis/testing/v1/rest hasn't been updated yet. I think we're blocked until gcloud CLI releases.

**Comment by Macarse** [comment]
@bootstraponline I guess we can start working on parsing the tests. What's on your mind? Should we depend on bluepill? Perhaps we should figure out how they do it and write the logic in kt. 
wdyt?

**Comment by bootstraponline** [comment]
yeah, we need a project like dex-test-parse for iOS. I think taking the bluepill code and printing the tests to stdout will be easy to start with. If the parsing logic is reasonable to implement in Kotlin then that may be a good next step.

**Comment by bootstraponline** [comment]
Looks like the xctestrun file can be parsed directly.

https://github.com/linkedin/bluepill/pull/162

**Comment by bootstraponline** [comment]
I updated the EarlGrey demo app to generate an xctestrun file:

- https://github.com/bootstraponline/EarlGrey/commit/43174c90ea13d72c212a5c624efd48e806aaf6c3
- Demo/EarlGreyExample/build.sh
- Demo/EarlGreyExample/run.sh

The test names end up in a binary file 
> ./EarlGrey/Demo/EarlGreyExample/xctestrun/Build/Products/Debug-iphonesimulator/EarlGreyExampleSwift.app/PlugIns/EarlGreyExampleSwiftTests.xctest/EarlGreyExampleSwiftTests

**Comment by bootstraponline** [comment]
These magic commands parse the tests from the binary:

> nm -gU 'EarlGreyExampleSwiftTests' | cut -d' ' -f3 | xargs -s 131072 xcrun swift-demangle | cut -d' ' -f3 | grep -e '[\\.|_]'test

```
EarlGreyExampleTestsSwift.EarlGreyExampleSwiftTests.testWithGreyAssertions()
EarlGreyExampleTestsSwift.EarlGreyExampleSwiftTests.testLayout()
EarlGreyExampleTestsSwift.EarlGreyExampleSwiftTests.testWithInRoot()
EarlGreyExampleTestsSwift.EarlGreyExampleSwiftTests.testCustomAction()
EarlGreyExampleTestsSwift.EarlGreyExampleSwiftTests.testWithCondition()
EarlGreyExampleTestsSwift.EarlGreyExampleSwiftTests.testBasicSelection()
EarlGreyExampleTestsSwift.EarlGreyExampleSwiftTests.testWithCustomMatcher()
EarlGreyExampleTestsSwift.EarlGreyExampleSwiftTests.testCollectionMatchers()
EarlGreyExampleTestsSwift.EarlGreyExampleSwiftTests.testCatchErrorOnFailure()
EarlGreyExampleTestsSwift.EarlGreyExampleSwiftTests.testWithCustomAssertion()
...
```

---

> NSString *swiftNmCmdline = @"nm -gU '%@' | cut -d' ' -f3 | xargs -s 131072 xcrun swift-demangle | cut -d' ' -f3 | grep -e '[\\.|_]'test";
> NSString *objcNmCmdline = @"nm -U '%@' | grep ' t ' | cut -d' ' -f3,4 | cut -d'-' -f2 | cut -d'[' -f2 | cut -d']' -f1 | grep ' test'";
>
> https://github.com/linkedin/bluepill/blob/master/Source/Shared/BPXCTestFile.m#L17-18

The workflow is:
- Find xctestrun, read `TestBundlePath` to locate `xctest`
- Parse test list from xctest binary file

**Comment by Macarse** [comment]
@bootstraponline amazing!
Plz add a couple of objective-c tests as well.

What about filtering? AFAIK, there is no concept of annotation. 
Should we only filter by package?

**Comment by Macarse** [comment]
@bootstraponline Thanks for the work!
