### ISSUE TITLE
Check budget before scheduling test run

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#192]
**Blocked on:  #139** *Test timing info is required to accurately understand cost.*

---

Limit break on cost instead of VM count. Now that we know the test timing info, it should be possible to estimate the potential cost.

```
budget: $2
```

This will proactively determine (using test timing) if the budget is expected to be exceeded.

Estimated cost is based on test time, shard count, and the device matrix.

- billing is done per minute (61 seconds = 2 billable minutes). Each shard increases the potential billable minutes
- Each device multiplies the cost

The final formula looks something like this:

totalTestTime * shardOverhead * deviceCount

Note that some devices are physical ($5/hr) and others are virtual ($1/hr). On iOS the devices are always physical.

**Comment by Chrizzzzzzz** [comment]
Specify in Flank.yaml what our budget is and then make sure that we don't run more VMs than our budget can handle.

If we attempt a run that is over our budget, Flank should notify us that the run is over budget and from there we should stop the run.

We are defining budgets in flank.yaml on a per-user per-run basis
