### ISSUE TITLE
Cancel builds on ctrl+c

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#194]
When cancelling the Kotlin process, it'd be nice if we also cancelled the running matrices. Additionally a `flank cancel` command could be added to cancel matrix ids in the most recent flank.json. That's useful for when async mode is used.

Cancel should work for both iOS and Android runs.

**Comment by Chrizzzzzzz** [comment]
We need to add an interrupt handler (Ctrl+C) as well as a `flank cancel` command. Firebase has a cancel API which we can interact with.

**Comment by bootstraponline** [comment]
```kotlin
try {
    GcTesting.get.projects().testMatrices().cancel(projectId, testMatrixId)
} catch (e: Exception) {
    try {
        GcTesting.get.projects().testMatrices().cancel(projectId, testMatrixId)
    } catch (e: Exception) {
        try {
            GcTesting.get.projects().testMatrices().cancel(projectId, testMatrixId)
        } catch (e: Exception) {

        }
    }
}
```

There may be a cleaner way to try/catch chain the cancel API. The above is what I used in the past.
