### ISSUE TITLE
Kotlin | Fix bug in gradle kotlin versions

### ISSUE THREAD

**Issue by rolyatwilson** [TestArmada/flank#195]
Builds fail when multiple projects (`kotlin_poc`, `xctest_parser`) both define:
```
kotlin("jvm") version Versions.KOTLIN
```

> Plugin request for plugin already on the classpath must not include a version

**Comment by bootstraponline** [comment]
I created a reduced test case and reported the bug upstream:
https://github.com/gradle/kotlin-dsl/issues/903

**Comment by bootstraponline** [comment]
Response is this isn't possible with subprojects. Composit builds will work

https://docs.gradle.org/current/userguide/composite_builds.html
