### ISSUE TITLE
Kotlin | Rewrite authentication docs

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#203]
Kotlin auth steps are reported as not working for some users. Try out the authentication process in a clean VM and update the docs.

**To Do**
- [x] service account
- [ ] user account

**Comment by Macarse** [comment]
Interesting comment from Paul Davis: 
```
Note: for gcloud, iOS beta access is granted per project.  For the Firebase web console, it is granted per email address.
```

**Comment by bootstraponline** [comment]
I wonder how much of the auth issues are iOS specific. 😄 I'll check that out tomorrow.

**Comment by Macarse** [comment]
It's just additional info.

**Comment by bootstraponline** [comment]
service account docs have been rewritten / verified as working: https://github.com/TestArmada/flank/pull/206

next is the user account doc.

**Comment by bootstraponline** [comment]
decided to support only service accounts, which is the official recommendation for using FTL in CI.
