### ISSUE TITLE
ServiceException: 409 bucket already exists

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#21]
> $ gsutil mb gs://delta-essence-114723-flank/
> Creating gs://delta-essence-114723-flank/...
> ServiceException: 409 Bucket delta-essence-114723-flank already exists.

We should probably check to see if the bucket exists before running the make bucket command.

**Comment by bootstraponline** [comment]
- https://github.com/GoogleCloudPlatform/gsutil/blob/master/gslib/tests/test_mb.py#L28

gsutil checks stderror for "bucket exists". The same fix would work for flank. If this message is detected, then remove it from the debug error output.

**Comment by renas** [comment]
Should be fixed now.
