### ISSUE TITLE
Kotlin | Support logging in as a user

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#211]
Edit: Decided to support service account authentication only.

Match the behavior of `gcloud auth login`

Clean up the working code in https://github.com/TestArmada/flank/pull/209

**Comment by Chrizzzzzzz** [comment]
Add support for generic project ids, not hardcoded to our project. We also need a fallback authentication if a service account exists we should use that instead of a google login.

We also need to add the *Flank auth* command

**Comment by bootstraponline** [comment]
Decided to support service account authentication only.
