### ISSUE TITLE
Kotlin | Allow gcs path to xctestrunZip

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#217]
xctestrunZip should accept a gcs path so we don't have to upload the zip every time.

```yaml
xctestrunZip: gs://apps/EarlGreyExample.zip
```

**Comment by vanwagonet** [comment]
@bootstraponline should we copy the zip to the new folder, or just skip that step entirely?

**Comment by bootstraponline** [comment]
> just skip that step entirely?

👍
