### ISSUE TITLE
Kotlin | Print actual cost of the run

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#232]
Now that Flank Kotlin supports multiple devices & platforms, the cost estimation is in need of updating. Using information from the device catalog we can accurately calculate the cost per run. Physical devices are billed at $5/hr and virtual devices are billed at $1/hr.

* Determine how many minutes is used per device type
  * iOS is always physical
* Calculate aggregate cost

2 hours on physical devices + 1 hour of virtual devices would be $11.

**Comment by inktomi** [comment]
It would also be great if we had the option to suppress this info so that it doesn't show. Not all teams want to have their devs thinking about cost :)

**Comment by bootstraponline** [comment]
That's great feedback, I agree a config option makes sense. If false then we'd skip printing the costs.
