### ISSUE TITLE
Kotlin | YAML compatibility with gcloud CLI

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#238]
**Blocked on: #224**

Flank YAML should be updated to be compatible with gcloud. Test by creating a YAML file and running it with both `gcloud` CLI and `flank`

I think we're using different naming conventions in a few places.

https://cloud.google.com/sdk/gcloud/reference/topic/arg-files

- [ ] TODO: Refactor away from generics and type casting

**Comment by vanwagonet** [comment]
Here's what the changes look like if I'm understanding right:

current|gcloud|notes
---|---|---
projectId|project|
devices|device|
appApk|app|
testApk|test|
xctestrunZip|test|
waitForResults|async|opposite
rootGcsBucket|results-bucket|
disablePerformanceMetrics|performance-metrics|opposite
disableVideoRecording|record-video|opposite
testTimeoutMinutes|timeout|resolve time units from string
testMethods|test-targets|class or package prefixed for android

Just camel to kebab:

current|gcloud
---|---
xctestrunFile|xctestrun-file
autoGoogleLogin|auto-google-login
useOrchestrator|use-orchestrator
directoriesToPull|directories-to-pull
environmentVariables|environment-variables

The gcloud yaml format seems to rely on having a top level key, which needs to be specified along with the file. Also`include:` seems to allow you to compose your config from other keys.

You are also allowed to specify `device-ids`, `os-version-ids`, `locales`, and `orientations` from which a device list is generated. Docs refer to this as "legacy" and says `device` is preferred. I'd suggest we only support `device`.

I'd assume we still want the camelCase variables in code, so we may need to individually annotate each renamed property.

**Comment by bootstraponline** [comment]
> You are also allowed to specify device-ids, os-version-ids, locales, and orientations from which a device list is generated. Docs refer to this as "legacy" and says device is preferred. I'd suggest we only support device.

Agreed.



> I'd assume we still want the camelCase variables in code, so we may need to individually annotate each renamed property.

Yeah, on Android we have a pattern of using annotations to keep the Kotlin style. 
https://camo.githubusercontent.com/a0be64856eabc22b783c450c77d581fb6fcc7b9b/68747470733a2f2f692e696d6775722e636f6d2f4378786d6e75312e706e67

I expect there's a similar feature for YAML parsing.

> Here's what the changes look like if I'm understanding right:

Thank you for writing out the table. I think this ticket is blocked on https://github.com/TestArmada/flank/issues/224 due to reusing the same key in different contexts.
