### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by leinardi** [TestArmada/flank#252]
I am getting this exception and I am not sure what is causing it:

```
$ java -jar flank-v2.0.3.jar -a app.apk -t test.apk

Running 292 out of 292 tests

Local 'flank.tests' found. It contains test execution times used to create shards with configurable durations. Default shard duration is 120 seconds.

Uploading: app.apk to: gs://blablabla-flank/2018-07-06_15:30:52.193000_rtYW/

Uploading: test.apk to: gs://blablabla-flank/2018-07-06_15:30:52.193000_rtYW/

java.lang.ArrayIndexOutOfBoundsException: 1
	at com.walmart.otto.shards.ShardCreator.createShardMap(ShardCreator.java:143)
	at com.walmart.otto.shards.ShardCreator.getConfigurableShards(ShardCreator.java:68)
	at com.walmart.otto.shards.ShardExecutor.executeShards(ShardExecutor.java:40)
	at com.walmart.otto.shards.ShardExecutor.execute(ShardExecutor.java:30)
	at com.walmart.otto.Flank.start(Flank.java:80)
	at com.walmart.otto.Flank.main(Flank.java:118)
```
I was able to run the tests twice before having this issue.

I tried to remove the `flank.tests` or add an empty one from the storage but I am still getting the Exception.

The `config.properties` is:
```
directories-to-pull=/sdcard
use-orchestrator=true
shard-timeout=10
shard-duration=120
devices=model:NexusLowRes;version:27;locale:de
debug-prints=false
fetch-xml-files=true
auto-google-login=true
fetch-bucket=false
aggregate-reports.enabled=false
```

The storage rules are:
```
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if false;
    }
  }
}
```
I tried also with `allow read, write: if request.auth != null;` but I get the same result.

The app and test apk have not changed since the last first two execution so, in theory, I only changed the `flank.tests`, the storage permission and the `config.properties`, but I am almost 100% positive that I have restored everything to the original value.

**Comment by bootstraponline** [comment]
Thanks for opening an issue. This is a bug in Flank Java that's been fixed in the Kotlin rewrite.

**Comment by leinardi** [comment]
Oh nice, is the Kotlin rewrite public? Does it have already reach a beta stability or is still too early to try it out?

Anyway I found that the issue was having an empty `flank.tests` inside the storage bucket. Probably the README.md should be update to make this sentence more clear:

> Create an empty flank.tests in the root Flank folder to start from a clean slate

Since the problem seems triggered by having the `flank.tests` inside the bucket root folder, I guess I have to create it in my local root folder. But I think it would make sense to properly handle an empty file also in the bucket folder.

**Comment by bootstraponline** [comment]
@leinardi we're in the Firebase slack `#flank` channel https://firebase.community/

Kotlin rewrite has been open source since the first commit. 🙂 

> But I think it would make sense to properly handle an empty file also in the bucket folder.

I agree. I'm happy to accept PRs. The Java version is no longer actively developed since the efforts are focused on the Kotlin version.

**Comment by bootstraponline** [comment]
The Kotlin rewrite is now available for testing and feedback. 
- https://github.com/TestArmada/flank/releases/tag/flank_snapshot

If this is still an issue in the new release, comment and let me know.
