### ISSUE TITLE
[Feature] Print command duration

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#27]
Gradle builds print time info:

```
 BUILD SUCCESSFUL
[22:54:52]: ▸ Total time: 4 mins 58.471 secs
```

It'd be nice to have a `Total time` that represents the amount of time from the start of flank until the end. Currently I have to wrap flank in a script to figure out how long we're waiting for flank to run the tests.

**Comment by abhagupta** [comment]
Isn't this the 'Combined execution time?'

**Comment by renas** [comment]
Good idea. We'll add it.

**Comment by bootstraponline** [comment]
> Isn't this the 'Combined execution time?'

No. I'm not sure why 'Combined execution time' exists. Here's a real example:

```

Billable time:  111.0 min(s)

Estimated cost:  $1.85(virtual) $9.25(physical)

Combined test execution time: ~41 minutes

End time: 2017-06-02_09:30
```

This command takes ~13 minutes to run. The printed information doesn't tell me that. `Billable time` is valuable because that's directly related to costs. End time and combined test execution time... I'm not sure what value there is for those numbers. It's possible there's a use case I'm unaware of.

**Comment by renas** [comment]
This has been added.
