### ISSUE TITLE
Matrix fails but MatrixResultsReport shows (100.00%) 

### ISSUE THREAD

**Issue by miguelslemos** [TestArmada/flank#277]
Hi, I'm facing a problem when running flank v3.0-SNAPSHOT, some matrix fails but MatrixResultsReport shows 14 / 14 (100.00%)

**Comment by miguelslemos** [comment]
I'm working on it, I'll open PR in soon

**Comment by bootstraponline** [comment]
Thanks, let me know if I can help.

**Comment by bootstraponline** [comment]
Fixed by https://github.com/TestArmada/flank/pull/279
