### ISSUE TITLE
findbugs warnings

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#28]
<img width="536" alt="find_bugs" src="https://cloud.githubusercontent.com/assets/1173057/26728945/e98fc742-4779-11e7-8b54-015f26e8afe1.png">

`./gradlew findbugsMain`

**Comment by renas** [comment]
Thanks. We'll fix them.

**Comment by bootstraponline** [comment]
fixed by https://github.com/TestArmada/flank/commit/d624f3dffe3103a5a85af499419890be4ea758ca
