### ISSUE TITLE
project premission?

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#30]
It looks like I'm not able to move cards across the board. 😭 

- https://github.com/TestArmada/flank/projects/1

**Comment by renas** [comment]
Do you know if there is way to give write access to just the board? If that
is not possible I have to get approval from legal :(

**Comment by bootstraponline** [comment]
I think if you add me as a read only collaborator, that will be sufficient. 

- https://help.github.com/articles/adding-outside-collaborators-to-repositories-in-your-organization/

**Comment by renas** [comment]
Sent you an invite.

**Comment by bootstraponline** [comment]
Thanks! Looks like GitHub's permissions model is a bit broken if they require write access for issue management. 

- https://help.github.com/articles/repository-permission-levels-for-an-organization/

**Comment by renas** [comment]
I totally agree with you.
