### ISSUE TITLE
ERROR: gcloud crashed (OperationalError): database is locked

### ISSUE THREAD

**Issue by wokkaflokka** [TestArmada/flank#307]
First off, I want to say thanks for building Flank. We've been using Flank for months now to great effect -- it's led to a dramatic reduction in build times for us.

### Issue

When running Flank during our CI process, we occasionally notice test failures where a subset of test shards fail to run. The log output for these failures looks like:

```
14:16:17 Gcloud command failed to run. Reporting that tests failed.
14:16:17 ERROR: gcloud crashed (OperationalError): database is locked
14:16:17 Gcloud command failed to run. Reporting that tests failed.
14:16:17 ERROR: gcloud crashed (OperationalError): database is locked
14:16:17 Gcloud command failed to run. Reporting that tests failed.
14:16:17 ERROR: gcloud crashed (OperationalError): database is locked
14:16:17 Gcloud command failed to run. Reporting that tests failed.
14:16:17 ERROR: gcloud crashed (OperationalError): database is locked
14:16:17 Gcloud command failed to run. Reporting that tests failed.
14:16:17 ERROR: gcloud crashed (OperationalError): database is locked
```

This error prevents builds from completing successfully.

#### Expected results

All tests run and build succeeds or fails on its own results.

#### Actual results

A subset of tests run. Build fails because Gcloud crashed.

### Additional Notes

* `Flank` Version: `2.0.3`
* OS: `Ubuntu 14`
* `Gcloud` Version: I'll have to look this up, it's installed on our Docker image using the latest Gcloud release. The last image was published around June.
* `flank.properties`:

```
devices=model:NexusLowRes;version:23;orientation:portrait;locale:en_US

environment-variables=coverage=true,coverageFile=/sdcard/tempDir/coverage.ec
directories-to-pull=/sdcard

numShards=18
shard-timeout=7
shard-duration=300

fetch-xml-files=false
fetch-bucket=false
debug-prints=false
gcloud-bucket=<REDACTED>
```

I'm hopeful this might be a misconfiguration on our end, but am open to any insights this team has to offer.

Thanks,
Emery Coxe

**Comment by Macarse** [comment]
it happens to us from time to time. I just restart the job or restart the computer running gcloud.

**Comment by wokkaflokka** [comment]
Thanks @bootstraponline for the prompt reply. Understood -- the recommended solution to this issue is to migrate to Flank 3. 

I've gone ahead and added support for Flank 3 to my CI/builds, and it's working at least at parity with Flank 2.0.3. I'll close this issue out.
