### ISSUE TITLE
Always emit aggregated junit.xml report

### ISSUE THREAD

**Issue by inktomi** [TestArmada/flank#314]
For integration with CI systems it's nice to have a report of all the tests that ran, and whether or not they passed. Currently, Flank only returns reports for tests that fail. 

Provide a flag that will result in a report of all the tests that ran & their status in a JUnit xml format.

**Comment by mrooney** [comment]
In case it is unclear, this is basically requesting the previously existing functionality of `fetch-xml-files=true` :)
