### ISSUE TITLE
Error when test apk has kotlin interfaces with @Test methods implementations

### ISSUE THREAD

**Issue by thalescm** [TestArmada/flank#35]
When flank generated the shards, firebase gave a `400` saying that the test is invalid.
[This gist](https://gist.github.com/thalescm/7e64bc80fc2a32dcb8eef50fc0a96aac) has the complete log.

The apks (with I already sent to @renas, if anyone want to test) run successfully on my machine.

It was also a bit hard to understand what logs are from what shard. Maybe putting a common prefix to logs about what shard they're refering to could help debugging.
E.g:
https://gist.github.com/thalescm/7e64bc80fc2a32dcb8eef50fc0a96aac#file-flank-shard-error-L51-L56
all lines could start with something like `SHARD X: <real log>`

**Comment by bootstraponline** [comment]
@thalescm is this still happening on master? I see a fix has landed.

- https://github.com/TestArmada/flank/commit/b41a9d97267a1ea55d02bbce29c3caaae5b33983

**Comment by renas** [comment]
Thanks for reporting this. Seems like the extraction of the test name is incorrect. We use this library for that:

https://github.com/linkedin/dex-test-parser

How should the below test look like in its correct form?

class com.nu.aab_transaction_detail.test_interface.InstallmentsAmountTest$DefaultImpls#testTransactionLoads_withInstallments_correctChargesSubtitleIsDisplayed

**Comment by thalescm** [comment]
@bootstraponline it was with the master version of 1 hour before I posted the issue.

**Comment by thalescm** [comment]
@renas I think I know what the problem is. `InstallmentsAmountTest` is a [kotlin interface](https://kotlinlang.org/docs/reference/interfaces.html].
There are some cases on the app where this behavior is present, so we extracted the test and it get tested on many different places. This way we don't have to rewrite the same test over and over.

Probably the lib does not identify that this is an interface and chooses this method to run, when it can't

**Comment by renas** [comment]
Yeah seems like it's not correctly identifying kotlin interfaces. If you can please submit this issue to the dex-test-parser project that would be great.

**Comment by thalescm** [comment]
Issue posted [there](https://github.com/linkedin/dex-test-parser/issues/3) I think it makes sense to close this issue once there's a fix there and is updated here as well. WDYT?

**Comment by bootstraponline** [comment]
Is this still an issue now that upstream is fixed?

**Comment by renas** [comment]
Will make a new release this week with the updated library.

**Comment by leandroBorgesFerreira** [comment]
Hi folks,

I'm facing this problem... 

I get: `Http error while creating test matrix: ResponseError 400:`

**Comment by bootstraponline** [comment]
Don't use @test on an interface.
