### ISSUE TITLE
Flag for specifying results directory 

### ISSUE THREAD

**Issue by rashiq** [TestArmada/flank#356]
We have a gcloud results directory that is very tied to how our CI setup works. We rsync everything from gcloud to `dir1/dir2`.

Flank also downloads test results and creates its own files (that we would like to incorporate into our CI as well), but they are located in `dir1/results`.

It would be cool to have a flag with which we could specify the results directory like this:

`java -jar flank.jar --config config.yml --results /dir1/dir2`

**Comment by bootstraponline** [comment]
`mv results/* dir2/`
