### ISSUE TITLE
Documentation for Appium support

### ISSUE THREAD

**Issue by dat-boris** [TestArmada/flank#374]
Thank you for such a great too!

From one of the [blog article](https://medium.com/walmartlabs/flank-smart-test-runner-for-firebase-cf65e1b1eca7)  I read from your team, I would like to double check if there's any Appium support to allow parallel test with flank.

If not wondering do you have any alternative suggestions on how your team automatically run your Appium tests on real device at the moment?  Thank you!

**Comment by bootstraponline** [comment]
hi, Firebase Test Lab doesn't support appium tests. Flank is a Firebase Test Lab runner, that means we're limited to what Firebase supports.

If Firebase adds Appium support then Flank will work with appium. I don't think that'll happen anytime soon though. Your best bet with appium is a provider such as bitbar, sauce labs test object, xamarin device farm, or similar.

In general I don't recommend appium as an automation technology. The native frameworks (Espresso, EarlGrey, XCUITest) are a better investment for performance and productivity.

**Comment by dat-boris** [comment]
> hi, Firebase Test Lab doesn't support appium tests. Flank is a Firebase Test Lab runner, that means we're limited to what Firebase supports.

That makes sense!  That's what I thought also and wondering if there's an alternative alluded to by the [blog article](https://medium.com/walmartlabs/flank-smart-test-runner-for-firebase-cf65e1b1eca7).

> In general I don't recommend appium as an automation technology. The native frameworks (Espresso, EarlGrey, XCUITest) are a better investment for performance and productivity.

Thank you for the frank suggestion.  I would agree for performance wise native frameworks is way better.  As the article suggests there's a factor of reusability, and maintainability that we are exploring also.

Feel free to close this issue - thank you!

p.s. We are at the stage of exploring Appium as a potential candidate so if you have any references as to horror stories of Appium uses would love to hear!  Thank you.

**Comment by bootstraponline** [comment]
I've spent some time exploring appium https://github.com/appium/appium/graphs/contributors

If you want developer involvement and the apps are native, then native is the way to go. If you have a react native app then detox will be a better fit. I'm not sure there's a great use case for appium today, maybe hybrid apps with webviews.

**Comment by sdg9** [comment]
I couldn't find it explicitly mentioned anywhere, but @bootstraponline regarding 

> If you have a react native app then detox will be a better fit

Does detox currently work with Flank on Firebase test lab, even if only virtual devices?
