### ISSUE TITLE
Add device info to HTML report

### ISSUE THREAD

**Issue by rpappalax** [TestArmada/flank#392]
After a test run our HTML reports list tests with failures.  This seems to be working as expected.  However, when you click on a test to view the details, the failure reason is often (not always) listed twice.

Example:
```
^ org.quest.johnny.activity.URLExceptionTest#AddAndRemoveExceptionTest(2)
android.support.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with text: is "Privacy & Security"
android.support.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with text: is "Privacy & Security"

^ org.quest.johnny.activity.ChangeSearchEngineTest#SearchSuggestionTest(2)
android.support.test.uiautomator.UiObjectNotFoundException: UiSelector[CLASS=android.widget.TextView, DESCRIPTION=localhost_42393, ENABLED=true]
android.support.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=org.mozilla.focus.debug:id/suggestionList]


^ org.quest.johnny.activity.ChangeSearchEngineTest#SearchTest(2)
android.support.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: '"Tab 1"' doesn't match: Tab 2
android.support.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: '"Tab 1"' doesn't match: Tab 2

^ org.quest.johnny.activity.SettingsBlockToggleTest#SettingsToggleTest(1)
android.support.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=org.mozilla.focus.debug:id/suggestionList]
```

**Comment by bootstraponline** [comment]
Can you send me your aggregated JUnit XML so I can debug?

**Comment by bootstraponline** [comment]
> ^ org.quest.johnny.activity.URLExceptionTest#AddAndRemoveExceptionTest(2)

what this means is the test `AddAndRemoveExceptionTest` executed twice `(2)`

are you using `repeatTests` in Flank?

**Comment by bootstraponline** [comment]
> repeat tests is set to: 1, i assume that means they should only run once

yep, XML merging bug then.

**Comment by bootstraponline** [comment]
Feature will be addressed in the new reporting experience. More details will be available next week.

**Comment by bootstraponline** [comment]
![image](https://user-images.githubusercontent.com/1173057/55266203-27cc3100-5252-11e9-87cb-57d439761bb1.png)
hey, device info is now in the HTML report 😄

**Comment by rpappalax** [comment]
Nice!!!  Thank you 🙏 

Pe 29 mar. 2019, la 15:41, bootstraponline <notifications@github.com> a scris:
