### ISSUE TITLE
gcloud auth login support

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#398]
Some teams don't allow sharing the service account json. Support user auth as an option in flank.

Requested by Slack.

Looking for additional feedback on if this is a useful feature to add or not. Code to add the feature is here: https://github.com/TestArmada/flank/pull/209

Update: Add this in Jan 2019

**Comment by freeamac** [comment]
This would be useful for debugging purposes as we also do not allow the sharing of the service account outside of the CI environment for Atlassian mobile products.

**Comment by bootstraponline** [comment]
The feature has been added in this pull request:
- https://github.com/TestArmada/flank/pull/449

will be merged after collecting feedback.

**Comment by freeamac** [comment]
Thank you!
