### ISSUE TITLE
Smart Flank - Dynamic bucket counts

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#399]
The current smart flank algorithm shards into user defined buckets based on time. A user may want to define a time value for buckets, and then let flank decide how many buckets to use.

Mention this in design doc. Maybe not for core flank due to resource exhaustion anti-pattern. Specifying a max shard may resolve the resource issue.

**Comment by Macarse** [comment]
Before jumping into the algorithm, I would like to define the variables for the yml file and how to process them.

We have `testShards` for SmartFlank based on shard count.
Should we use `shardTime` and `maxShards`?

Basically, `testShards` should NOT be present to run the dynamic algorithm. If we can't fit the tests based on the `shardTime` inside a `maxShards` count, we would do Smart Flank for count with `testShards == maxShards`

The other possibility is: `shardTime` in conjunction with `testShards`.
If `shardTime` is present, we try to create less shards than `testShards` and if we fail, we do Smart Flank for count with `testShards` as before.

I prefer the latter.

**Comment by bootstraponline** [comment]
There's a cost associated with excessive sharding so providing a limit there seems valuable. `-1` would represent unlimited.

I think `testShards` and `shardTime` make sense. Ideally with the default name on android using the APK bundle ID (fetched via FTL API), we would turn on smart flank by default. Meaning no configuration is required to reach optimal performance. Then users can turn down the limits as necessary.
