### ISSUE TITLE
No tests?

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#4]
It looks like the [only test flank has is empty?](https://github.com/TestArmada/flank/blob/180582392263cea6560680e400ff81d3118f9359/Flank/src/main/test/com/walmart/otto/FlankTest.java)

It'd be nice to setup some E2E tests on Travis CI [using encrypted variables](https://docs.travis-ci.com/user/environment-variables/).

**Comment by renas** [comment]
This we definitely need.

**Comment by bootstraponline** [comment]
Flank kotlin has some tests now, including a mocked server. :)
