### ISSUE TITLE
Smart Flank - Default smartFlankGcsPath name

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#401]
See if Firebase's default history name/gcs bucket is sufficient for smart flank by default.

`defaultBucket/defaultHistoryName_platform`

Android - package id
iOS - bundle id

Thoughts: try to make it work out of the box, iOS will be difficult for multi-targets in same binary.

Update: FTL API doesn't appear to have support for deriving a name from a binary. Moving to Flank v4.2 for now.

Update 2: This API is available for Android (parsing APK manifest) and not iOS.

**Comment by Macarse** [comment]
@inktomi I think README never hold any information regarding smartFlank.
Are you refering to https://github.com/TestArmada/flank/blob/master/docs/smart_flank.md ?

**Comment by inktomi** [comment]
Ah, that could be.  Apologies! I'm writing some docs and thought it had
been in the readme!

**Comment by Macarse** [comment]
Not sure why it's not in the README tbh. Perhaps we can put it under `EXPERIMENTAL`.
@bootstraponline what do you think?

**Comment by bootstraponline** [comment]
I thought it was in the readme as well! I think we should add it and collect feedback.

**Comment by bootstraponline** [comment]
If/when FTL adds a similar public API for iOS then I think it'd make sense to add to Flank. At the moment we'd only be able to provide a default for Android.
