### ISSUE TITLE
iOS - Preserve SkipTestIdentifiers when generating xctestrun

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#433]
`xctestrun` file generated by Xcode includes tests in `SkipTestIdetifiers` section, i.e.:
        
```
<key>SkipTestIdentifiers</key>
<array>
  <string>a/b</string>
</array>
```

Flank incorrectly strips the `SkipTestIdentifiers` section.

**Comment by ceaglest** [comment]
+1, I have ran into this issue as well. Our current workaround is to comment out skipped tests in code instead of using `SkipTestIdentifiers`.

**Comment by paynerc** [comment]
@ceaglest I should have known you would comment as soon as I sent you the link. 😆 

But yet, this would be a super awesome fix for us.

**Comment by bootstraponline** [comment]
> Our current workaround is to comment out skipped tests in code

That's what we've been doing at Instructure. I'll try and get this fixed in the next Flank release.

**Comment by bootstraponline** [comment]
I added a test, it looks like `SkipTestIdentifiers` is being preserved. 

@ceaglest @paynerc Would you help me reproduce the bug by providing your xctestrun files? For bonus points, modify the JUnit test in this PR to fail.

https://github.com/TestArmada/flank/pull/434

**Comment by bootstraponline** [comment]
Fixed in https://github.com/TestArmada/flank/pull/435

The snapshot jar is building now. Try it and let me know if the issue still exists.

https://github.com/TestArmada/flank/releases/tag/flank_snapshot

**Comment by ceaglest** [comment]
We are consuming 4.1.1 and it is working well for dynamically generated test cases and a sharding factor of 1.

We will try using SkipTestIdentifiers next week. Thank you!
