### ISSUE TITLE
Can we download all "directories-to-pull"?

### ISSUE THREAD

**Issue by winterDroid** [TestArmada/flank#438]
When using "directories-to-pull" it would be nice to also download all the fetched artifacts. What do you think about that?

**Comment by bootstraponline** [comment]
I think it may make sense to have a `directories-to-download` param. The benefit of having two params is fine grain control over what gets pulled & downloaded.

Downloading all directories every time may not be desired (and that conflicts with gcloud CLI's behavior).

Would that work for you?

**Comment by winterDroid** [comment]
That would be great to have!

**Comment by bootstraponline** [comment]
Awesome. If you want to submit a PR, it'll happen faster. :) Otherwise I'll take a look the second week of January 2019.

**Comment by bootstraponline** [comment]
Implemented in https://github.com/TestArmada/flank/pull/441
