### ISSUE TITLE
Enable user supplied shards.json

### ISSUE THREAD

**Issue by mrooney** [TestArmada/flank#44]
We'd love to be able to specify a json file of shards and have Flank use that. Motivation:

1. supports teams who want deterministic test groups and orders
2. allows for teams to implement their own sharding algorithms which can write this file out in a previous step

This could be configured via a `shardManifest=path/to/shards.json` in the config.properties. Example test JSON file:

```
[
  [
    "com.example.android.app.androidapp.ApplicationTest",
    "com.example.android.app.view.activity.LoginFlowTest",
    "com.example.android.app.view.activity.LogoutFlowTest"
  ],
  [
    "com.example.android.app.view.activity.SplashScreenTimeoutTest",
    "com.example.android.app.view.activity.HomeFlowTest"
  ]
]
```
If you would be interested in this feature, I am happy to attempt a pull request or work with an existing flank contributor to do so :)

**Comment by bootstraponline** [comment]
I think if this feature gets added, then we'd want to use `dex-test-parser` to validate the specified tests exist in the test apk.

**Comment by mrooney** [comment]
That seems reasonable. If I sent a PR along for this, do you think it would be accepted upon successful review? Happy to do it but don't want to do a bunch of work if it won't be accepted :)

**Comment by renas** [comment]
@mrooney it would be cool feature to have. Please submit a PR.

**Comment by bootstraponline** [comment]
I think this will be taken care of in the new client/server gRPC architecture. Users will be able to define a custom client that shards however you want.

#286 is tracking research on the new architecture
