### ISSUE TITLE
iOS support globs (*) for test-targets

### ISSUE THREAD

**Issue by gtroshin** [TestArmada/flank#467]
It is a feature request. 

Now only support:

```
test-targets:
    - ClassTest/testMethod
```

Would be good to have:

```
test-targets:
    - Class1Test/*
    - Class2Test/testLogin*
```

**Comment by bootstraponline** [comment]
I agree, that'd be a cool feature to add.

**Comment by bootstraponline** [comment]
Regex support for filtering iOS test targets will land on master soon. The glob example looks like this when translated to regex:

```
test-targets:
    - Class1Test/.*
    - Class2Test/testLogin.*
```
