### ISSUE TITLE
PollMatrices output stuck even if there is progress and FTL finished some matrix

### ISSUE THREAD

**Issue by gtroshin** [TestArmada/flank#468]
Flank CLI stuck without output of progress while some matrix still running but many of them have been finished. Maybe there is a way to print progress more frequently? 

Here is an example how it looks like. But actually, many more of the matrix has been finished successfully. 
Usually, workaround `no_output_timeout` for CI works to prevent timeout fail of CI. 

<img width="693" alt="image" src="https://user-images.githubusercontent.com/26898804/51430987-2e6f7400-1c23-11e9-9a51-5f56ca7c39dc.png">

And after it finished it printed rest of matrix statuses. But with long delay and only at the end.

<img width="711" alt="image" src="https://user-images.githubusercontent.com/26898804/51431029-c53c3080-1c23-11e9-86f8-366830611921.png">

**Comment by bootstraponline** [comment]
> Maybe there is a way to print progress more frequently?

If we printed a dot on every poll, would that help? Currently Flank will poll the first in progress every 15 seconds. After that matrix is finished, then Flank will start polling the next matrix.

The entire polling strategy will be replaced later this year. Currently the system is based on polling matrices individually. For 10 matrices, we'll sequentially go through the list and only move onto the next one until the current matrix reports `FINISHED`. There are limitations on the FTL server side that make more frequent polling not recommended.

**Comment by gtroshin** [comment]
I understand. I think printing something or statuses about how all running matrices are going would be good idea. It is not critical for me at least since CI usually have `no_output_timeout` without any limitation. 

> If we printed a dot on every poll, would that help?

I think - yes.

**Comment by Macarse** [comment]
@gtroshin I think you issue is that shards are taking too long. Can't you shard a bit more? What are you doing that tests are taking so long?

**Comment by gtroshin** [comment]
> @gtroshin I think your issue is that shards are taking too long. Can't you shard a bit more? What are you doing that tests are taking so long?

I think it was also related to the issue with FTL when there were Infrastructure failures caused by "too many screenshots" I have done with XCTContext. 
Here more details: https://firebase-community.slack.com/archives/C1MTSQ5QT/p1547810953226500 Now it got fixed and tests are fast + Flank output regularly.

**Comment by bootstraponline** [comment]
Great, it sounds like this issue is safe to close. If this becomes a problem again, let us know.
