### ISSUE TITLE
Snapshot Flank prints wrong version but correct commit sha

### ISSUE THREAD

**Issue by gtroshin** [TestArmada/flank#492]
`wget --quiet https://github.com/TestArmada/flank/releases/download/flank_snapshot/flank.jar ./flank.jar`

then

`java -jar flank.jar -v`

```
v4.2-SNAPSHOT
bed21aeb1c530c2e6740df88fe5214e877b1061c
```

The latest version now is 4.3.1

**Comment by bootstraponline** [comment]
![image](https://user-images.githubusercontent.com/1173057/52487794-69165d80-2b8c-11e9-919d-a41b57d65551.png)

Thanks for reporting! I updated the release process to tag the snapshots as `flank_snapshot`. The snapshots don't really have a version that corresponds to them. The version number is the SHA.
