### ISSUE TITLE
"All tests filtered out" error

### ISSUE THREAD

**Issue by rpappalax** [TestArmada/flank#497]
When I run my flank.yml with the flank.jar (4.3.1), it outputs the test config and then terminates locally with the message:  "All tests filtered out."  When I run the same flank.yml config with gcloud directly, the tests begin execution on Firebase and record the execution log (even though the test fails on Firebase).

**Comment by bootstraponline** [comment]
After debugging, I think we concluded this was a configuration error. I have a PR that'll be merged soon which makes common errors a little bit more user friendly.

- https://github.com/TestArmada/flank/pull/507
