### ISSUE TITLE
Junit report missing one test

### ISSUE THREAD

**Issue by AndreSand** [TestArmada/flank#499]
Looks like one test is missing inside JunitReport.xml. My Test suite is 24 tests, Firebase TestLab also shows 24 tests, but on the local flank report is missing one test, it shows 23 tests.

**Comment by bootstraponline** [comment]
I haven't been able to reproduce this. Can you send me on Slack your `results/` zip so I can investigate what's going on?

**Comment by bootstraponline** [comment]
I looked at the results zip on Slack and didn't see any junit XML files. Once I have more info I'm happy to research further. So far no additional reports of this bug have been logged.

**Comment by bootstraponline** [comment]
The combined XML logic is moving to the server which I expect will resolve this issue. I haven't been able to reproduce merging problems locally.

If you're still seeing the issue on Flank v8.0.1 or newer, let me know.
