### ISSUE TITLE
Allow /results to be stored to different local path

### ISSUE THREAD

**Issue by Harlekwin** [TestArmada/flank#500]
Currently all of the Flank test results seem to be stored to /results

It would be nice if we had and optional parameter to set a different local folder to write the results to.

**Comment by bootstraponline** [comment]
I think something like `flank-result-dir: $BITRISE_DEPLOY_DIR` would replace the need for 

`cp -r ./apps/student/results/*/* $BITRISE_DEPLOY_DIR`

**Comment by bootstraponline** [comment]
https://github.com/TestArmada/flank/pull/523 will fix this :)
