### ISSUE TITLE
Publish JAR on Maven

### ISSUE THREAD

**Issue by winterDroid** [TestArmada/flank#508]
Instead of just publishing the JAR on Github, can it be also published on MavenCentral or similar? This would allow users to depend on it in a Gradle task with a specific configuration dependency to let Gradle download it: https://discuss.gradle.org/t/running-an-executable-jar-from-a-remote-maven-repo/15444

**Comment by winterDroid** [comment]
Alternatively the project could be also just made compatible with https://jitpack.io/. See https://jitpack.io/docs/BUILDING/#custom-commands on how to customize the build command.

**Comment by bootstraponline** [comment]
I had setup jitpack before. Flank is not a dependency. It's a stand alone CLI tool. There's also no official Gradle integration. We had a lot of weird support requests about people adding Flank to their app with Gradle.

I think https://github.com/runningcode/fladle is what you want.

**Comment by winterDroid** [comment]
Haha yeah that's what we want to use it for since it uses a SNAPSHOT version of a download task to download the JAR from the releases. If the releases would be published to maven, Gradle could fetch them directly instead which would be much cleaner.

**Comment by bootstraponline** [comment]
Does it make a difference to you if they're on jcenter maven or jitpack?

**Comment by winterDroid** [comment]
Usage wise not, but I guess mavenCentral would be the most trustworthy. @runningcode mentioned some security concerns with jitpack.

**Comment by bootstraponline** [comment]
Yeah I'm not sure I trust jitpack's build environment. It's also painful for consumers if they only need one dep from jitpack.

I'll take this as a feature request to automate jcenter publishing like dex-test-parser does.

**Comment by winterDroid** [comment]
Why do you prefer jcenter over mavenCentral?

**Comment by bootstraponline** [comment]
Maven Central is a bit of a nightmare to publish to. In general artifacts tend to end up on jcenter instead. It's still a maven repo.

**Comment by winterDroid** [comment]
Yeah but it was less reliable in the post - for us it was often not reachable. But anyway, having it on jcenter or mavenCentral would be great

**Comment by bootstraponline** [comment]
@winterDroid See if this works for you

https://bintray.com/flank/Flank/Flank/v4.4.0

If so I'll automate future publishes like this:

> jfrog bt upload --publish flank.jar flank/Flank/Flank/v4.4.0

jcenter is the Android Studio default now I think.

**Comment by runningcode** [comment]
Thanks for publishing! What are the maven coordinates for flank?

**Comment by bootstraponline** [comment]
maven {
         url  "https://dl.bintray.com/flank/Flank"
     }

compile "flank:Flank:v4.4.0"

I think something like that. I'll try it tomorrow

**Comment by runningcode** [comment]
I tried the following:
```
maven {
url "https://dl.bintray.com/flank/Flank"
}
maven {
url "https://dl.bintray.com/flank"
}
maven {
url "https://dl.bintray.com/"
}

implementation "flank:Flank:v4.4.0"
```

I got an error as follows:
```
CONFIGURE FAILED in 8s
Could not find flank:Flank:v4.4.0.
Searched in the following locations:
  - file:/Users/no/.gradle/caches/5.2.1/embedded-kotlin-repo-1.3.20-2/repo/flank/Flank/v4.4.0/Flank-v4.4.0.jar
  - https://dl.google.com/dl/android/maven2/flank/Flank/v4.4.0/Flank-v4.4.0.pom
  - https://dl.google.com/dl/android/maven2/flank/Flank/v4.4.0/Flank-v4.4.0.jar
  - https://jcenter.bintray.com/flank/Flank/v4.4.0/Flank-v4.4.0.pom
  - https://jcenter.bintray.com/flank/Flank/v4.4.0/Flank-v4.4.0.jar
  - https://oss.sonatype.org/content/repositories/snapshots/flank/Flank/v4.4.0/Flank-v4.4.0.pom
  - https://oss.sonatype.org/content/repositories/snapshots/flank/Flank/v4.4.0/Flank-v4.4.0.jar
  - https://dl.bintray.com/flank/Flank/flank/Flank/v4.4.0/Flank-v4.4.0.pom
  - https://dl.bintray.com/flank/Flank/flank/Flank/v4.4.0/Flank-v4.4.0.jar
  - https://dl.bintray.com/flank/flank/Flank/v4.4.0/Flank-v4.4.0.pom
  - https://dl.bintray.com/flank/flank/Flank/v4.4.0/Flank-v4.4.0.jar
  - https://dl.bintray.com/flank/Flank/v4.4.0/Flank-v4.4.0.pom
  - https://dl.bintray.com/flank/Flank/v4.4.0/Flank-v4.4.0.jar
```

Are we sure that `dl.bintray.com` is a maven repo?

**Comment by bootstraponline** [comment]
This should be working now. I setup a gradle publish task.

https://github.com/TestArmada/flank/pull/509

```
repositories {
    maven(url = "https://dl.bintray.com/flank/maven")
}

dependencies {
    compile("flank:flank:4.4.0")
}
```
