### ISSUE TITLE
Execute Additional Test apks

### ISSUE THREAD

**Issue by inktomi** [TestArmada/flank#511]
For projects that have many modules it's not uncommon to include some small number of android tests in a submodule. Flank is currently unable to run these tests because they are not packaged in the main app's test apk. 

In order to run these tests today, a user would need to write a script that passes each library to flank along with the main app's apk for the "app". This is doable, but it would be better if flank could handle this for us. 

I'd like to propose the following: 

1. A new `--module-apks` parameter in the Flank yaml. This is a `List<String> = emptyList()`
1. Modify `AndroidArgs` so that it's a data class, allowing us to use things like `copy`
1. `AndroidArgs` needs to be updated to allow the `app` parameter to be adjusted on the fly  
1. Update `AndroidTestRunner` to upload the new APKs in the same way the main app apk is uploaded today. 
1. Update `AndroidTestRunner` to iterate through the `--module-apks` and pass each to the `AndroidArgs` before creating a `GcAndroidTestMatrix` for the shards created in each additional apk. 

The changes to `AndroidTestRunner` would be something along these lines: 

    suspend fun runTests(androidArgs: AndroidArgs): MatrixMap = coroutineScope {
        val (stopwatch, runGcsPath) = GenericTestRunner.beforeRunTests(androidArgs)

        val jobs = arrayListOf<Deferred<TestMatrix>>()

        // Add all the app tests. 
        jobs.addAll(runTestsInternal(androidArgs, runGcsPath))

        // Add any submodule tests as well.
        val resolvedModuleUris = resolveSubmoduleApks(androidArgs, runGcsPath)
        resolvedModuleUris.forEach { apk ->
            // Submodules package everything they need in the test apk, we can use any random app apk
            val moduleArgs = androidArgs.copy(testApk = apk)

            jobs.addAll(runTestsInternal(moduleArgs, runGcsPath))
        }

        GenericTestRunner.afterRunTests(jobs.awaitAll(), runGcsPath, stopwatch, androidArgs)
    }

Things to consider.. 
1. I'm not really sure modifying the `AndroidArgs` like this is the best option, but not doing it this way requires that we also modify the sharding logic so that we can track which APK a given test is part of so that a shard does not span more than one apk. Since the sharding logic is built into the AndroidArgs, copying them and allowing it to re-run against a new APK seems to work. 

I'd like to work on this, so please let me know if anyone has better ideas on how this might be implemented. I've sort of hacked together the above solution - it's _very_ hacky but it does work and I could clean it up for a PR if it sounds good.

**Comment by runningcode** [comment]
Sort of related to this: https://github.com/runningcode/fladle/issues/7#issuecomment-467989675

One workaround is to use fladle and apply the fladle plugin to every module. You can then run a gradle command which runs all the tests in one gradle command.

**Comment by inktomi** [comment]
Ah, yea - is that a supported use case though? It seems like you'd end up needing to deal with a lot of chunks of results - one per execution. I was trying to think of a solution that we could build inside Flank to do the same thing as fladle#7 is doing via separate invocations.

**Comment by bootstraponline** [comment]
I'm open to thinking about how to solve this in Flank. In the best case situation though, this is a feature request for FTL. If FTL had API support for the use case then Flank integration is trivial.

**Comment by inktomi** [comment]
I completely agree - I can raise an issue on their tracker and I'll link it here for more discussion.

**Comment by inktomi** [comment]
I opened a discussion on https://issuetracker.google.com/issues/122327486 since there's not an exsisting issue and this one is very much related. I also mentioned it in the test-lab Firebase slack.

**Comment by inktomi** [comment]
In talking to William Hester it seems like this is not something that FTL itself can support in the near future. I think it makes sense to build this on top of FTL, or as part of Fladle - let me know, I'm happy to open a PR.

**Comment by bootstraponline** [comment]
Let's build this into flank. Let me know when you have some time to chat about the design

**Comment by bootstraponline** [comment]
For the design, what do you think of this?

```yaml
flank:
  additional-apks:
  - app: ../test_app/apks/app-debug2.apk
    test: ../test_app/apks/app-debug-androidTest2.apk
  - test: ../test_app/apks/app-debug-androidTest3.apk
```

If app is omitted then we'll use the `gcloud: app: ...`.

**Comment by winterDroid** [comment]
Are you planning to support also multiple `app`s? Or just one `app` and multiple `test` apks?

**Comment by winterDroid** [comment]
AFAIK GCloud beta does [support additional APKs](https://cloud.google.com/sdk/gcloud/reference/beta/firebase/test/android/run#--additional-apks).

**Comment by bootstraponline** [comment]
> It seems gcloud beta does support [additional APKs](https://cloud.google.com/sdk/gcloud/reference/beta/firebase/test/android/run#--additional-apks).

gcloud supports installing additional APKs but they don't run them.

> Are you planning to support also multiple `app`s? Or just one `app` and multiple `test` apks?

I'm thinking if we support this, then it should be for an array of app/test pairs. If the app is omitted then we'll use the default app for the provided test apk.

**Comment by inktomi** [comment]
The additional apks from FTL are useful only for allowing you to fill out an inter-app dependency - not for providing additional tests in a secondary apk. The testing APIs offered by FTL via gcloud / rest are targeted at the APK you upload as the main app/test apk. This is one of the topics I discussed with the FTL team. 

I think if we want to allow multiple **app** definitions then we should think about making those a _Pair_ internally so that we can track the main app/test combination. _app_ is a required parameter to run tests in FTL, so we always need to know which one to use even if we make parallel internal executions. 

Android libraries package all their logic and tests into a single apk, which means we can use any random _app_ with a library _test_ apk and tests will still execute. That's not the case with an _Application_ module test apk, which requires the matching _app_.

**Comment by bootstraponline** [comment]
Discussed on slack to call this `additional-app-test-apks:` to differentiate from FTL's `--additional-apks` which installs but doesn't run the apks.
