### ISSUE TITLE
Flank YAML backwards compatibility

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#515]
Flank is a mature enough project where a backwards compatibility strategy is necessary to avoid breaking users as changes are made.

**Ideas**

- Print to log when deprecated keys are used
- Support legacy key names until the next major release
- Auto rewrite YAML file to use the new keys (either automatically or on demand via doctor command)

If a user has a legacy key name that's no longer supported, what should we do?

- Exit with an with an error message?
- Auto rewrite YAML to the new key name (if auto migration is possible)?
- Continue to run but ignore the key and print a warning to standard out

**Out of scope**

- CLI flags are not part of the backwards compatibility commitment

**Comment by valeraz** [comment]
I would go with:
- deprecation warning on console
- support for legacy functionality for 1 major release
- on-demand fixing of the configs (as opposed to automatic)
- exiting with an error message once the legacy value is no longer supported
