### ISSUE TITLE
Exception in thread "main" picocli.CommandLine$ExecutionException

### ISSUE THREAD

**Issue by cavega** [TestArmada/flank#517]
I reported an issue to Firebase Test Lab where my Test lab runs for Android are returning 503s with `com.google.api.client.googleapis.json.GoogleJsonResponseException`. The last response I got from the Firebase team is that they opened an [issue](https://status.firebase.google.com/incident/Test%20Lab/19006) on their dashboard with description `Test Lab is having an issue with Cloud Storage and have paused the queues until the issue is resolved. Your tests will queue and may time out.`. They seem to indicate that the issue could affect my Flank runs. Just posting the issue here for reference.

**Comment by bootstraponline** [comment]
Thanks for posting. When the FTL service has an outage then Flank stops working.

**Comment by cavega** [comment]
Definitely. Just wanted to post the info here for record keeping in case it happens again. They restored the service and everything is working as expected. Thanks.
