### ISSUE TITLE
Add support for parallel Cucumber scenarios 

### ISSUE THREAD

**Issue by FreddieCarre** [TestArmada/flank#528]
<h1>Flank and Cucumber</h1>

[cucumber-android](https://github.com/cucumber/cucumber-android) now allows use of Orchestrator and test sharding, I would like to then run these tests in parallel with Firebase.

It would be great if Flank worked for these tests, currently it doesn't find the tests (I assume because it's expecting JUnit 3 and 4 tests) and as a result, runs them all as a single shard.

Please see the below output seen when trying to run the project's 150 tests as 4 shards.

```
>>$ java -jar ~/flank.jar firebase test android run
AndroidArgs
    gcloud:
      results-bucket: test-lab-bucket
      results-dir: null
      record-video: true
      timeout: 15m
      async: false
      project: project-id
      results-history-name: null
      # Android gcloud
      app: ./app/build/outputs/apk/debug/app-debug.apk
      test: ./app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
      auto-google-login: true
      use-orchestrator: true
      environment-variables:
        clearPackageData: true
      directories-to-pull:

      performance-metrics: true
      test-targets:

      device:
        - model: Pixel2
          version: 28
          locale: en
          orientation: portrait
      flaky-test-attempts: 2

    flank:
      testShards: 4
      shardTime: 600
      repeatTests: 1
      smartFlankGcsPath: 
      files-to-download:

      test-targets-always-run:

      disableSharding: false
RunTests
  Uploading app-debug.apk .
  Uploading app-debug-androidTest.apk .

  Smart Flank cache hit: 0% (0 / 16)
  Shard times: 160s

  16 tests / 1 shard
```

**Comment by bootstraponline** [comment]
How do these Cucumber steps show up to [dex-test-parse](https://github.com/linkedin/dex-test-parser)? The parallel execution feature is based on reading the dex byte code.

If the byte code parser can't find them, then Flank doesn't currently have a way of running the tests in parallel. Project Nitrogen is coming later this year and that'll allow us to support more use cases.

**Comment by FreddieCarre** [comment]
They aren't returned. I believe dex-test-parse is picking up references to JUnit TestCase class and `@Test` annotations.

Thanks for getting back to me. I will try again with Project Nitrogen.

**Comment by bootstraponline** [comment]
Thanks. Once nitrogen is released, let me know how that goes.
