### ISSUE TITLE
What is the reason to require paid Firebase plan?

### ISSUE THREAD

**Issue by artem-zinnatullin** [TestArmada/flank#53]
TL;TR: we want *sometimes* run our instrumentation tests in Firebase, but most of the time run them on internal emulators pool.

So we're completely fine with free plan quotas but Flank requires paid plan (for Google Cloud Storage bucket I guess).

What is the reason to require paid plan and can this be fixed to allow test runs on free plan? Thanks!

**Comment by bootstraponline** [comment]
FTL provides a free bucket by default. If flank stops specifying a bucket then that should enable free tier tests to run.

This seems like a good feature to add.
