### ISSUE TITLE
Observing that logcat/ video and other artifacts are not being created for all the shards

### ISSUE THREAD

**Issue by prolificcoder** [TestArmada/flank#54]
Hello,
Thanks for the great project and open-sourcing it. I have been successfully able to run our entire suite of ~60 tests with minimal effort locally and also on our Jenkins. 
I am observing a rather strange behavior: All the tests though executed in a separate matrix are essentially showing the same artifacts including logcat/video.mp4 file. In the gsutil pull down command I can clearly see only one video file being generated. 

```
[android] Copying gs://gdm-android-telephony-flank/2017-07-24_21:37:29.481000_AdAA/Nexus6P-25-en-portrait/test_result_7874888483897436532.xml...
[android] Copying gs://gdm-android-telephony-flank/2017-07-24_21:37:29.481000_AdAA/Nexus6P-25-en-portrait/test_result_9131515297737460228.xml...
[android] Copying gs://gdm-android-telephony-flank/2017-07-24_21:37:29.481000_AdAA/Nexus6P-25-en-portrait/test_result_8667431412748016253.xml...
[android] Copying gs://gdm-android-telephony-flank/2017-07-24_21:37:29.481000_AdAA/Nexus6P-25-en-portrait/test_result_8330274942631895392.xml...
[android] Copying gs://gdm-android-telephony-flank/2017-07-24_21:37:29.481000_AdAA/Nexus6P-25-en-portrait/test_result_9101555559323915915.xml...
[android] Operation completed over 49 objects/16.2 KiB.                                    
[android] Copying gs://gdm-android-telephony-flank/2017-07-24_21:37:29.481000_AdAA/Nexus6P-25-en-portrait/artifacts/com.godaddy.gdm.telephony.uitests.SwitchAccountNumberTest-switchAccountTest-switchAccountTest-1.jpg...
[android] Copying gs://gdm-android-telephony-flank/2017-07-24_21:37:29.481000_AdAA/Nexus6P-25-en-portrait/artifacts/video.mp4...
[android] Copying gs://gdm-android-telephony-flank/2017-07-24_21:37:29.481000_AdAA/Nexus6P-25-en-portrait/artifacts/coverage.ec...
[android] Copying gs://gdm-android-telephony-flank/2017-07-24_21:37:29.481000_AdAA/Nexus6P-25-en-portrait/bugreport.txt...
[android] Copying gs://gdm-android-telephony-flank/2017-07-24_21:37:29.481000_AdAA/Nexus6P-25-en-portrait/logcat...
[android] Copying gs://gdm-android-telephony-flank/2017-07-24_21:37:29.481000_AdAA/Nexus6P-25-en-portrait/instrumentation.results...
```

When I open the test_results file I can clearly see that tests are being executed and some have proper failure logs with them. But I can't find the test being executed in logical. Is there a setting I am missing? 

My config.properties look pretty normal

```
deviceIds=Nexus6P
os-version-ids=25
orientations=portrait  
locales=en
environment-variables=coverage=true,coverageFile=/sdcard/coverage.ec
directories-to-pull=/sdcard
shard-timeout=5 
shard-duration=-1

numShards=  
shardIndex= 
debug-prints=true
fetch-xml-files=true
fetch-bucket=false
gcloud-path=
gsutil-path=
```

do let me know what details you need to diagnose this problem.

**Comment by renas** [comment]
Thanks for reporting this. Please add: "fetch-bucket:true" to your config.properties to download the artifacts.

**Comment by prolificcoder** [comment]
What I am saying is that even in the google play UI for test lab it is showing the wrong video/logt 
eg: see below even though there are bunch of tests executed
![image](https://user-images.githubusercontent.com/149176/28592525-1e13244e-713e-11e7-81b9-af31f83bc4cf.png)
There are only 3 artifacts

![image](https://user-images.githubusercontent.com/149176/28592542-32a167fe-713e-11e7-8ffc-773b482afa55.png)
 and that video.mp4 is from one test that is shown in all the matrices of that flank run

**Comment by renas** [comment]
Please submit this issue to the Firebase team.
