### ISSUE TITLE
Pass multiple values to --test-targets argument via CLI 

### ISSUE THREAD

**Issue by v-ahadke** [TestArmada/flank#562]
I am trying to use the flank to run the iOS UITests on Firebase Lab. My test suite contains more than 100 tests out of which I need to run only few tests dynamically as per business logic. I am able to use `-test-targets` in yml file but I am trying to pass these values via CLI so that dynamic values can be passed. I tried multiple ways but firebase runs all the tests. Below are the few formats I have used but no luck,

1) `java -jar flank.jar firebase test ios run --config ./fastlane/flank.ios.yml --test-targets MyClassA/testA --test-targets MyClassB`
2) `java -jar flank.jar firebase test ios run --config ./fastlane/flank.ios.yml --test-targets [MyClassA/testA,MyClassB]`
3) `java -jar flank.jar firebase test ios run --config ./fastlane/flank.ios.yml --test-targets: MyClassA/testA,MyClassB`

Can you please let me know what is correct format to run only few tests via CLI? Thanks

**Comment by bootstraponline** [comment]
`--test-targets=a,b,c` is the syntax for using the CLI.

https://github.com/TestArmada/flank/blob/ca27667180a5c941f362ca2cc79d3d9aa6a77924/test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt#L174

You can also use a regular expression. Let me know if that helps.
