### ISSUE TITLE
Passing the --test & --xctestrun-file via CLI not working

### ISSUE THREAD

**Issue by v-ahadke** [TestArmada/flank#564]
When I pass the `--test` & `--xctestrun-file` via CLI , it exits the command with `test is not set` message. So looks like https://github.com/TestArmada/flank/blob/380de617040ab049de94491e4911d97b83e6630f/test_runner/src/main/kotlin/ftl/args/yml/IosGcloudYml.kt#L33 & https://github.com/TestArmada/flank/blob/380de617040ab049de94491e4911d97b83e6630f/test_runner/src/main/kotlin/ftl/args/yml/IosGcloudYml.kt#L34 causing the issue. 

If I understand the code correctly, it expects the yml file must have entries for https://github.com/TestArmada/flank/blob/380de617040ab049de94491e4911d97b83e6630f/test_runner/src/main/kotlin/ftl/args/yml/IosGcloudYml.kt#L29 which will restrict user to pass them via CLI.

Can someone please check this? Thanks

**Comment by bootstraponline** [comment]
Thanks for the feedback! I will fix this in https://github.com/TestArmada/flank/pull/566 and make a new release today.

**Comment by bootstraponline** [comment]
The issue has been resolved in https://github.com/TestArmada/flank/releases/tag/v6.2.2
