### ISSUE TITLE
How can I use smart flank to reduce the cost of the devices

### ISSUE THREAD

**Issue by moatazeldebsy** [TestArmada/flank#573]
I'm using Flank in running our tests using Firebase Test Lab but I need to use Smart Flank to reduce the cost of devices, how can I do that ?

**Comment by bootstraponline** [comment]
```yaml
  ## Google cloud storage path to store the JUnit XML results from the last run.
  smart-flank-gcs-path: gs://tmp_flank/flank/test_app_ios.xm
```

If you set the GCS path for smart flank, then flank will store the test timing info there and use it when generating shards.

See `max-test-shards` and `shard-time` from the readme as well.

We have a #flank channel on firebase test lab which is a good place to ask general questions.
https://firebase.community/
