### ISSUE TITLE
Run all tests on all devices

### ISSUE THREAD

**Issue by plastiv** [TestArmada/flank#578]
I can't seem to figure out how to run all tests on every device in matrix. 

Use case: we want to run our test suite on `min` and `max` supported sdks to check on the boundaries. For our app we want to run all tests on `sdk=21` and `sdk=28`. But as soon as I add second device it starts sharding the tests or use only single emulator.

**Comment by bootstraponline** [comment]
By default Flank runs all tests on all devices. The tests may be split across multiple copies of the same device. If you don't want sharding, you can disable that:

```yaml
flank:
  disable-sharding: false
```

Is there a reason you don't want sharding? That's the fastest way to get coverage across multiple SDK versions.

**Comment by bootstraponline** [comment]
![image](https://user-images.githubusercontent.com/1173057/62436532-f686d480-b70d-11e9-8dae-c5d2a779b9da.png)
![image](https://user-images.githubusercontent.com/1173057/62436540-fbe41f00-b70d-11e9-94e5-dc14a15b9dac.png)
![image](https://user-images.githubusercontent.com/1173057/62436543-00a8d300-b70e-11e9-8aaa-64d55d28020c.png)

Here's an example using the Flank sample app. All tests are run on all devices & API levels. If you have more questions, checkout the #flank channel on the Firebase community Slack. http://firebase.community
