### ISSUE TITLE
Print location of HTMLErrorReport when finished.

### ISSUE THREAD

**Issue by runningcode** [TestArmada/flank#592]
Would it be possible to print out the location of the HTMLErrorReport.html when finished and if it is generated.
I got this feature request a couple times in Fladle. 🤣  https://github.com/runningcode/fladle/issues/64

**Comment by runningcode** [comment]
Would you be able to provide some more information? Is this a feature which would fit on your roadmap and something you have time for or would you prefer external contributions?
Should this feature be behind a flag, or enabled for all?

**Comment by bootstraponline** [comment]
![image](https://user-images.githubusercontent.com/1173057/66669484-7a78a380-ec0c-11e9-9461-4067219be557.png)

I fixed this in #612, it'll be in the next Flank release.

**Comment by runningcode** [comment]
Would it be possible to print the fully qualified path? This makes it
easier to click on the HTML report from the terminal output.

bootstraponline <notifications@github.com> schrieb am Fr., 11. Okt. 2019,
11:51:

**Comment by bootstraponline** [comment]
> Would it be possible to print the fully qualified path?

Sure, I'll update to print the full path.

**Comment by runningcode** [comment]
You on fire! :)

bootstraponline <notifications@github.com> schrieb am Fr., 11. Okt. 2019,
12:02:
