### ISSUE TITLE
Flank is unable to fetch results after test run.

### ISSUE THREAD

**Issue by artem-zinnatullin** [TestArmada/flank#60]
We have two projects where we use Flank, one of them works fine, but another fails to fetch test run results. Projects have identical Flank configuration except `gcloud-bucket`.

After all tests pass Flank crashes with following log:

```java
Created folder: /project/instrumentation-tmp/results

Fetching results to: /project/instrumentation-tmp/results
java.lang.RuntimeException: CommandException: No URLs matched: flank.tests
	at com.walmart.otto.tools.Tool.executeCommand(Tool.java:60)
	at com.walmart.otto.tools.GsutilTool.uploadTestTimeFile(GsutilTool.java:81)
	at com.walmart.otto.Flank.uploadTestTimeFile(Flank.java:151)
	at com.walmart.otto.Flank.start(Flank.java:65)
	at com.walmart.otto.Flank.main(Flank.java:77)
```

Environment: 

- Flank 1.4.1
- Google Cloud SDK 149.0.0-linux-x86_64

I've also double checked `gcloud-bucket` and gcloud `--key-file`, it seems to be a Flank issue since it's able to run tests but unable to download results.

**Comment by renas** [comment]
Thanks for reporting this. We'll fix this ASAP.

**Comment by artem-zinnatullin** [comment]
If you need more info — feel free to ask, I'll be glad to help!

**Comment by artem-zinnatullin** [comment]
Tried to update Google Cloud SDK to 167.0.0-linux-x86_64 — same error.
