### ISSUE TITLE
Download URL 404'ing

### ISSUE THREAD

**Issue by ferrous777** [TestArmada/flank#600]
`0.20s$ wget --verbose https://github.com/TestArmada/flank/releases/download/flank_snapshot/flank.jar -O ./flank.jar
--2019-09-11 19:45:12--  https://github.com/TestArmada/flank/releases/download/flank_snapshot/flank.jar
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-09-11 19:45:12 ERROR 404: Not Found.
The command "wget --verbose https://github.com/TestArmada/flank/releases/download/flank_snapshot/flank.jar -O ./flank.jar" failed and exited with 8 during .`

In our CI Process, the flank url for latest snapshot is throwing a 404. Has this url been deprecated?

**Comment by bootstraponline** [comment]
The bitrise release step is broken. I recommended using a stable version of Flank until I replace the bitrise step.

**Comment by ferrous777** [comment]
Yay! Thanks!

**Comment by bootstraponline** [comment]
I replaced the bitrise step with GitHub's official hub tool: https://github.com/github/hub

The snapshot releases are now working again. Let me know if you see any other issues.
