### ISSUE TITLE
Release the latest version of flank to fix the - Unrecognized field "testLabExecutionId" issue

### ISSUE THREAD

**Issue by narenkmanoharan** [TestArmada/flank#601]
Currently, our prod testing env is broken because of the same issue we saw a couple of days ago. The fixes for the issue have been merged into master:

 - https://github.com/TestArmada/flank/pull/597
 - https://github.com/TestArmada/flank/pull/599

Would it be possible to cut a new release with the fixes?

**Comment by bootstraponline** [comment]
As of ~32 minutes ago, FTL finished rolling back the change. All Flank versions should be working now. For details, see #test-lab in the Firebase community Slack.

If your tests are still broken let me know so I can escalate with Google.

A new release is on my task list, the Bitrise CI system used for releases broke.

**Comment by bootstraponline** [comment]
Flank v8 has been released:

![image](https://user-images.githubusercontent.com/1173057/66529705-49d42500-eab9-11e9-88f1-205b27060b4f.png)


I replaced the Bitrise step with [GitHub's hub tool](https://github.com/github/hub) and the releases are auto published once again.
