### ISSUE TITLE
`test-targets` does not support `filter` option supported by AndroidJUnitRunner

### ISSUE THREAD

**Issue by dbarwacz** [TestArmada/flank#604]
I'm evaluating flank as a replacement for our current stack. 
We'd like to write (and apply) complex rules that will allow us to define what should be tested (ie. dynamic forms e2e and corresponding functional tests) in a way that does not constraint us. So far, I believe the only way to achieve that is by using `org.junit.runner.manipulation.Filter`. 

Would it be difficult to add that support in https://github.com/TestArmada/flank/blob/0a7b34f5e4f116de8dc388d114a6c21036d3b3ca/test_runner/src/main/kotlin/ftl/filter/TestFilters.kt? 

Is it something non-trivial that's hard to do, or it was just skipped because it wasn't worth implementing yet? If this is just a matter of crafting (relatively easy) implementation, I'm happy to help.

**Comment by bootstraponline** [comment]
I think it'd be easy to add. You'll want to include JUnit tests to verify the feature works. I have been transitioning to a new role so I haven't had as much time for Flank development. I am actively reviewing pull requests and responding to issues.

If you join the https://firebase.community/ there's a #flank channel where the developers answer questions.

**Comment by dbarwacz** [comment]
Thank you, I setup project locally and briefly looked into it. My conclusion is that it's not trivial though, is it? I need to find referenced class, but I'm in the context of runner, so source code will not be available. I would need to find that class in tested apk, extract it and run somehow. Am I missing something here?

**Comment by bootstraponline** [comment]
I think there are a few options:

1) Implement the test selection logic in a custom test runner that Flank passes data through
2) Pre-process the list of tests, then pass on that list to Flank. It should be easy to spin up a local emulator and run whatever test filtering code you need to output the final list of tests.
3) If everything can be determined statically via bytecode analysis then extending the `TestFilters.kt` in flank would work. It sounds like what you want is runtime analysis.

What I've seen companies do is either approach `1)` or `2)`, meaning they use custom code to generate the list of tests (which can execute on device) and then pass on the final list of tests to Flank. For `2)` that's a matter of having a test runner that understands how you want to filter the tests, then passing on the environment variables through similar to AJUR sharding.

I think that should answer your question.

**Comment by bootstraponline** [comment]
AST parsing may be another way. Dropbox recently open sourced their test filtering solution:

https://github.com/dropbox/hypershard-android

Your arbitrary code would execute, then generate a `flank.yml` that flank runs on Firebase Test Lab.

**Comment by bootstraponline** [comment]
If you have additional questions, let me know. The current sharding approach requires knowing a list of tests in advance. Flank currently uses binary parsing. I think the AST approach would meet your use case as you could generate a flank.yml file using arbitrary criteria.
