### ISSUE TITLE
Support Parametrized

### ISSUE THREAD

**Issue by dsvoronin** [TestArmada/flank#61]
While running tests in FTL with and without Flank i see some tests not running in Flank case:
seems all of them has `@RunWith(Parameterized::class)` in common.

Is it possilble to support them?

**Comment by renas** [comment]
Thanks for reporting this. We use this library: https://github.com/linkedin/dex-test-parser to parse the tests. 

Please submit the issue to them. As soon as they fix it we will include it into Flank.

**Comment by bootstraponline** [comment]
I don't think an issue for parameterized tests was ever submitted upstream.

**Comment by zlippard** [comment]
According to this: https://github.com/linkedin/dex-test-parser/issues/17 @parameterized is already supported by the parser library.

**Comment by bootstraponline** [comment]
https://github.com/TestArmada/flank/issues/255 should fix this then. I know they fixed some bugs in 2.0

I'm currently on a different project (getting iOS tests going with EarlGrey) so it'll be a few weeks before I'm back on Flank. Happy to merge a PR if you want to update the dependency and see what happens.

**Comment by zlippard** [comment]
Thanks, I'll work on the PR and see how it goes!

**Comment by bootstraponline** [comment]
There's a #flank channel in the [Firebase Test Lab slack](https://firebase.community/) if you have questions. I think it should be a one line change to the [build.gradle.kts file.](https://github.com/TestArmada/flank/blob/master/cloud_testing/kotlin_poc/build.gradle.kts)

**Comment by zlippard** [comment]
ok great, will reach out to that channel with any questions!

**Comment by bootstraponline** [comment]
Hi, thanks for opening an issue on the Flank repo. The Kotlin rewrite is now available for testing and feedback. This replaces the Java version of Flank.

- https://github.com/TestArmada/flank/releases/tag/flank_snapshot

Join us in the`#flank` channel on the Firebase slack to chat. If this is still an issue in the new release, comment and let me know.

-  https://firebase.community/
