### ISSUE TITLE
MALFORMED_APK error with 8.0.1

### ISSUE THREAD

**Issue by elihart** [TestArmada/flank#613]
We have been using 7.0.2 with no problems, but I just tried updating to 8.0.1 and all of our test matrices now fail with MALFORMED_APK.

The output looks like this:
```
[2019-10-14T15:21:52Z] PollMatrices
--
  | [2019-10-14T15:21:52Z]   0m  0s matrix-xx53sc5snocka blueline-28 VALIDATING
  | [2019-10-14T15:22:08Z]   0m 15s matrix-xx53sc5snocka blueline-28 Error: MALFORMED_APK
  | [2019-10-14T15:22:08Z]   0m 15s matrix-xx53sc5snocka blueline-28 INVALID
  | [2019-10-14T15:22:08Z]   0m 15s matrix-xx53sc5snocka INVALID
```

I didn't see anything in release notes that suggests I should have had to change anything to be compatible with the update, so I'm not sure what's going on.

**Comment by bootstraponline** [comment]
Thank you for opening an issue! MALFORMED_APK is an error from the Firebase Test Lab server. The best way to get additional context is to post the matrix id in the #test-lab channel on the [Firebase Community Slack](https://firebase.community/).

**Comment by elihart** [comment]
Thanks for pointing me that way.

It seems like this is also happening with 7.0.2, and it was just a coincidence that it started right when I updated :P
