### ISSUE TITLE
Combined Test Reports

### ISSUE THREAD

**Issue by Mauin** [TestArmada/flank#62]
In the Medium article about flank (https://medium.com/walmartlabs/flank-smart-test-runner-for-firebase-cf65e1b1eca7) a paragraph describes that flank should output a JUnit report as if all tests were run on a single device.

However when I'm running all tests with flank I'm only getting all the `*.xml` reports for the testsuite and no combined report.

Is there a flag that I'm missing to generate this report? Or what is the preferred way to combine all the XML reports to one unified HTML report?

**Comment by renas** [comment]
There is no way to combine them from Flank. We use Jenkins for our CI and Jenkins combines them automatically and shows all the results together in the results view.
