### ISSUE TITLE
Flank doesn't support testInstrumentationRunnerArguments

### ISSUE THREAD

**Issue by yaroslav-shlapak** [TestArmada/flank#624]
I'm trying to run tests with flank with next line in android defaultConfig:
`testInstrumentationRunnerArguments annotation: "androidx.test.filters.LargeTest"`
but it seems that flank ignores this line and runs all tests, even not annotated with @LargeTest. The `app:connectedAndroidTest` works as expected.
Does flank support testInstrumentationRunnerArguments? Is it possible to achieve tests filtering by flank with some gradle configuration?

**Comment by bootstraponline** [comment]
Are you able to get this working with gcloud CLI? Flank supports test filtering by annotation. I'll post an example.

**Comment by bootstraponline** [comment]
```yaml
  ## A list of one or more test target filters to apply (default: run all test targets).
  ## Each target filter must be fully qualified with the package name, class name, or test annotation desired.
  ## Supported test filters by am instrument -e … include:
  ## class, notClass, size, annotation, notAnnotation, package, notPackage, testFile, notTestFile
  ## See https://developer.android.com/reference/android/support/test/runner/AndroidJUnitRunner for more information.
  # test-targets:
  #  - class com.example.app.ExampleUiTest#testPasses
```

**Comment by yaroslav-shlapak** [comment]
I 

> Are you able to get this working with gcloud CLI? Flank supports test filtering by annotation. I'll post an example.

I was able to get the `testInstrumentationRunnerArguments annotation: "androidx.test.filters.LargeTest"`  working with  `app:connectedAndroidTest` but not with `app:execFlank`. 
I managed to get it working according to my usecase by adding testTargets to my configuration, but I thing flank should also honor settings in default config.

**Comment by bootstraponline** [comment]
Flank matches https://cloud.google.com/sdk/gcloud/reference/firebase/test/android/run

I don't think gcloud supports `testInstrumentationRunnerArguments`

**Comment by yaroslav-shlapak** [comment]
> Flank matches https://cloud.google.com/sdk/gcloud/reference/firebase/test/android/run
> 
> I don't think gcloud supports `testInstrumentationRunnerArguments`

Well, ok than, hope it'll help someone in future. Thanks for quick responses @bootstraponline !
