### ISSUE TITLE
support android test orchestrator flag

### ISSUE THREAD

**Issue by mrooney** [TestArmada/flank#63]
[Google Cloud SDK 167](https://cloud.google.com/sdk/docs/release-notes): "Promoted Firebase Test Lab to beta for running instrumentation test with Android Test Orchestrator. Use --use-orchestrator to run with Orchestrator."

This ["allows you to run each of your app's tests within its own invocation of Instrumentation"](https://developer.android.com/training/testing/junit-runner.html#using-android-test-orchestrator) and avoid shared state and crashes taking out other tests.

Would it be possible to have a configuration option for enabling this?

**Comment by renas** [comment]
Absolutely. We'll add it.

**Comment by renas** [comment]
@mrooney only the alpha and beta versions of gcloud CLI supports --use-orchestrator. We'll add it when it makes it to the final release.

**Comment by geaden** [comment]
Hi @renas! It seems `gcloud` CLI now supports `--use-orchestrator` flag in the release version: https://cloud.google.com/sdk/gcloud/reference/firebase/test/android/run

**Comment by renas** [comment]
Awesome. We'll add support.
