### ISSUE TITLE
cost estimate on Jenkins error

### ISSUE THREAD

**Issue by StevenUpForever** [TestArmada/flank#72]
When set `config.properties` like `deviceIds=Nexus5X,Nexus6P
os-version-ids=23,24
orientations=portrait
locales=en,sv
`
The cost on Jenkins will looks like `00:41:10 Billable time: 0.0 min(s) 
00:41:10 
00:41:10 Estimated cost: `

**Comment by abhagupta** [comment]
This is happening because gcloud seems to have a bug , it does not display the Time each tests take when there are more than 1 device. I have put a solution to not display the Billable time and Estimated Cost when this happens.

**Comment by renas** [comment]
Fixed in 2.0.0
