### ISSUE TITLE
How many numShards to use?

### ISSUE THREAD

**Issue by Macarse** [TestArmada/flank#77]
I am trying out flank for the first time.
What should be my guideline?

**Comment by rciovati** [comment]
If you want a cost-effective approach just let Flank calculate the best number for you.

**Comment by Macarse** [comment]
@rciovati how? afaik not setting the number of shards creates a device per test.

**Comment by rciovati** [comment]
@Macarse The first time you run Flank it uses one device per test, records the tests runtime and generates a `flank.tests` file that will be used to calculate how to group your tests in the following runs. Make sure you have that file in the folder where you run Flank or in the Google Cloud Storage bucket.

**Comment by Macarse** [comment]
@rciovati Thanks for your answer.
What happens when I run flank for a third time and the apk includes additional tests?
Are those new test run in a single shard and measured? Is the file updated on every run?

**Comment by renas** [comment]
Each new test will be executed in its own shard so that its execution time can be saved in flank.tests. Next time flank is used it will know how long the test took to execute and it can package it correctly.
