### ISSUE TITLE
Fetch coverage.ec to results directory

### ISSUE THREAD

**Issue by geaden** [TestArmada/flank#78]
Coverage is fetched as bucket artifact, but it can take significant time to fetch all the artifacts just to get coverage results. It'll save some build time if coverage is fetched along with test_results

**Comment by renas** [comment]
We'll add support for this.

**Comment by ScottPierce** [comment]
Is there an ETA on this? This is actually what we are actively trying to do currently.

**Comment by bootstraponline** [comment]
I'd suggest joining us in the Flank channel on the firebase slack if you're not there already.

https://firebase.community

**Comment by bootstraponline** [comment]
Hi, thanks for opening an issue on the Flank repo. The Kotlin rewrite is now available for testing and feedback. This replaces the Java version of Flank.

- https://github.com/TestArmada/flank/releases/tag/flank_snapshot

Join us in the`#flank` channel on the Firebase slack to chat. If this is still an issue in the new release, comment and let me know.

-  https://firebase.community/
