### ISSUE TITLE
Skipping tests in certain package

### ISSUE THREAD

**Issue by Macarse** [TestArmada/flank#79]
I have some tests used by fastlane+screengrab which should not be ran by flank.

I would like to have a `skip-tests` in the config file specifying the package of the tests which shouldn't be run.  What do you think?

Also, is there a reason why the package which should be run are not part of the config file instead of the command line args?

Thanks!

**Comment by renas** [comment]
Good idea. We'll add support for this.

**Comment by Macarse** [comment]
I can help with a PR. 

Let me know if this makes sense to you:

In cfg, I would add:
skip-tests=com.package1,com.package2

To filter tests out I would change the `filterTests` method in `FilterUtils` to:

```
public static List<String> filterTests(List<String> testNames, List<String> skipNames, String packageName)
```

**Comment by renas** [comment]
Sounds good to me. Thanks for contributing.

**Comment by Macarse** [comment]
README should be updated

**Comment by renas** [comment]
@Macarse readme will be updated shortly. We'll make a new relase this week.
