### ISSUE TITLE
Add --no-record-video config option

### ISSUE THREAD

**Issue by geaden** [TestArmada/flank#81]
There was added support of passing the argument [`--no-record-video`](https://firebase.googleblog.com/2017/10/firebase-test-lab-october-2017-update.html). It would be great to pass it with flank to get faster test results

**Comment by bootstraponline** [comment]
FTL is recommending not to use this option due to a known bug with AVD disconnects.

**Comment by geaden** [comment]
@bootstraponline Thanks! Didn't know this. Then closing the issue

**Comment by bootstraponline** [comment]
It's probably good to keep the issue open. We'd still want to add this feature eventually (once the bug is fixed).
