### ISSUE TITLE
After flank 1.5.0 tests fail to execute on gcloud

### ISSUE THREAD

**Issue by prolificcoder** [TestArmada/flank#86]
I've recently upgraded to flank 1.5.0 and started seeing the following output 
```
Executing shard 107:  com.godaddy.gdm.telephony.WebSocketTest#testIncomingSmsWebSocket


Fetching bucket to: /Users/smalugu/code/gdm-android-telephony/bucket

Billable time: 0.0 min(s)

Estimated cost:

[2017-12-02_09:13] Total time: 0 min, 25 sec
```
When I check google firebase console, I see no tests. If I change to flank 1.4.0 tests run just fine. 

My config.properties look like this
```
deviceIds=NexusLowRes
os-version-ids=25
orientations=portrait  
locales=en
environment-variables=^:^coverage=true:coverageFile=\"/sdcard/coverage.ec\":notAnnotation=android.support.test.filters.FlakyTest,com.godaddy.gdm.telephony.uitests.testcategories.DeviceOnlyTests
directories-to-pull=/sdcard
shard-timeout=5 
shard-duration=-1

numShards=  
shardIndex= 
debug-prints=false
fetch-xml-files=false
fetch-bucket=true
gcloud-path=
gsutil-path=
```
I also tried changing to new syntax for devices and that didn't help. Is there something I am missing?

**Comment by renas** [comment]
Flank 1.5.0 requires gcloud sdk >= 176.0.0. Please update your sdk and let me know if it works. One tip is to enable debug in config.properties so you see all the error messages.

**Comment by prolificcoder** [comment]
yes you are correct. thanks for the prompt response!
