### ISSUE TITLE
config.properties should be a parameter

### ISSUE THREAD

**Issue by Macarse** [TestArmada/flank#89]
In my setup, I will have a different cfg for ci and a different cfg for regression testing. Example, I want ci to run in a single locale / single device.

What do you think of removing all the parameters we have right now and force a config.

so instead of:
```
java -jar Flank.jar <app-apk> <test-apk> [package-name]
```

it would be:
```
java -jar Flank.jar myConfig.properties
```

properties file should have new keys:
`app_apk_path`, `tests_apk_path`, `use_tests_in_packages` to map the previous parameters

**Comment by renas** [comment]
Flank will automatically pickup a properties file if it exists. So depending on which flank.properties you have it will use that. We could add a parameter to point out a specific file but we want to keep the current CLI. So I'll close this ticket.

**Comment by Macarse** [comment]
@renas Should I create a new ticket? Happy to work on it but I would like to polish requirements.

**Comment by runningcode** [comment]
I would also like this feature! :)

**Comment by renas** [comment]
@Macarse Sure please create a ticket. Would be good to be able to point to a config file.

**Comment by Macarse** [comment]
@renas can you specify how would you like the CLI to be?

```java -jar Flank.jar <app-apk> <test-apk> <config-path> [package-name]```
looks messy.

would you prefer to add https://pholser.github.io/jopt-simple and do something like:
```java -jar Flank.jar -a <app-apk> -t <test-apk> -c <config-path> -p [package-name]```

Let me know and I can create the ticket with the proper requirement.

**Comment by runningcode** [comment]
The second options with the `-c` i think is better for my use case especially since it might be an optional argument.
The only downside is that it would break backward compatibility, but I think its the right choice.

**Comment by rciovati** [comment]
@Macarse I think the second option is better. The first one still introduce a breaking change so IMHO it is worth to take the time and implement a solution that is more robust and extensible.

**Comment by Macarse** [comment]
What about the other params? Are you OK with -a -t and -p?

On Jan 3, 2018 03:14, "Riccardo Ciovati" <notifications@github.com> wrote:

@Macarse <https://github.com/macarse> I think the second option is better.
The first one still introduce a breaking change so IMHO it is worth to take
the time and implement a solution that is more robust and extensible.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/TestArmada/flank/issues/89#issuecomment-354965840>, or mute
the thread

**Comment by renas** [comment]
@Macarse I agree the second option is best.

**Comment by renas** [comment]
@Macarse yes those are fine. @rciovati are you also working on this?

**Comment by rciovati** [comment]
>What about the other params? Are you OK with -a -t and -p?

To me -p is a bit confusing because it could potentially be a package name or also the fully qualified name of a single test, but I guess we could come up with a better naming in #90.

@renas I am not working on this but we have some capacity and we are really interested in getting the #90 done, so I could work on this task. But since it's a @Macarse proposal I guess he wants to work on it :)

**Comment by renas** [comment]
@rciovati ok great. In that case we can do what is left of #90 after @Macarse finishes this and we can have a deeper look at the naming scheme. The more clear we can make the naming the better it is.

**Comment by Macarse** [comment]
@renas @rciovati what letter would you use for `[package-name]`?

I will create a ticket to add the `jopt-simple` dependency with `-a -t -c -p` and @rciovati can add more params in #90

**Comment by renas** [comment]
@Macarse cool. Lets do -p for now and then we can have a deeper look at this when adding the other params in #90

**Comment by renas** [comment]
Please don't make any changes to the README at this time. I'll update it later on when we release 2.0 that includes these updates.

**Comment by Tapchicoma** [comment]
Please update readme with `-c` option, version 2.x was released :slightly_smiling_face:

**Comment by bootstraponline** [comment]
If you want to send a pull request, I'll merge it. :)
