### ISSUE TITLE
Add more tests filtering options

### ISSUE THREAD

**Issue by rciovati** [TestArmada/flank#90]
At current state, Flank supports running tests based on:
- package (single)
- class (single)
- test name (single)

It's possible to filter tests in such a way passing the package parameter when invoking Flank. 
In addition to that is possible to run all but some tests defining the `skip-tests` property in the config file.

Taking inspiration from what [AndroidJunitRunner](https://developer.android.com/reference/android/support/test/runner/AndroidJUnitRunner.html) supports, we could add these execution options:
- running multiple tests
- running all tests in multiple classes
- running all tests except those in a particular class
- running all but a single test
- running all tests except a particular package
- running all tests with a given annotation(s)
- running all tests without a given annotation(s)

Related to https://github.com/TestArmada/flank/issues/89#issuecomment-354918303, since it would require a new CLI arguments mechanism.

**Comment by renas** [comment]
@rciovati This would be a great addition! I like the CLI suggested by @Macarse as it will make it more clear what is passed in.

**Comment by rciovati** [comment]
Fixed in #93
